BEGIN;
ALTER TYPE "ShoppingListSortOption"
RENAME VALUE 'REV_ALPHABETICAL' TO 'REVERSE_ALPHABETICAL';

ALTER TYPE "ShoppingListSortOption"
RENAME VALUE 'REV_CREATION_DATE' TO 'REVERSE_CREATION_DATE';
COMMIT;
