// Disclaimer: A decent portion of this file was generated using AI

export type CategoryKeywordSeed = {
  keyword: string;
  weight: number;
  categorySlug: string;
};

export const categoryKeywords: CategoryKeywordSeed[] = [
  // ============================================================
  // FROZEN FOODS
  // ============================================================
  { keyword: "frozen", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen food", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen foods", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen meal", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen meals", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen pizza", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen chips", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen fries", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen vegetables", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen veg", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen berries", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen fruit", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen pastry", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen dessert", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen desserts", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "ice cream", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "icecream", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "gelato", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "sorbet", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen chicken", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen beef", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen pork", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen lamb", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen fish", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen seafood", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen prawns", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen shrimp", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen dumplings", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen spring rolls", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen nuggets", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen lasagne", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen lasagna", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen pie", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen pies", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen sausage rolls", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen waffles", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen hash browns", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "hash browns", weight: 1, categorySlug: "frozen_foods" },
  { keyword: "frozen blueberries", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen strawberries", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen spinach", weight: 2, categorySlug: "frozen_foods" },

  // ============================================================
  // DAIRY / EGGS / CHEESE
  // ============================================================
  { keyword: "milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "full cream milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "full cream", weight: 1, categorySlug: "dairy_eggs_cheese" },
  { keyword: "skim milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "skimmed milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "light milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "lactose free milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "lactose-free milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "soy milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "soya milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "oat milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "almond milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "rice milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "coconut milk", weight: 1, categorySlug: "dairy_eggs_cheese" },
  { keyword: "butter", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "salted butter", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "unsalted butter", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "margarine", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "egg", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "eggs", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "free range eggs", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "free-range eggs", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "organic eggs", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "yoghurt", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "yogurt", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "greek yoghurt", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "greek yogurt", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "natural yoghurt", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "natural yogurt", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "cream", weight: 1, categorySlug: "dairy_eggs_cheese" },
  { keyword: "thickened cream", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "double cream", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "heavy cream", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "sour cream", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "cooking cream", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "cottage cheese", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "cheese", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "cheddar", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "cheddar cheese", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "sliced cheese", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "grated cheese", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "mozzarella", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "parmesan", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "brie", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "camembert", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "feta", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "ricotta", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "cream cheese", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "mascarpone", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "goat cheese", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "blue cheese", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "halloumi", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "custard", weight: 1, categorySlug: "dairy_eggs_cheese" },

  // ============================================================
  // FRUIT / VEG
  // ============================================================
  { keyword: "apple", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "apples", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "banana", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "bananas", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "orange", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "oranges", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "mandarin", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "mandarins", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "lemon", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "lemons", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "lime", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "limes", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "avocado", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "avocados", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "tomato", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "tomatoes", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "potato", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "potatoes", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "sweet potato", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "sweet potatoes", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "carrot", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "carrots", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "onion", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "onions", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "red onion", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "garlic", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "ginger", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "broccoli", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "cauliflower", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "spinach", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "lettuce", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "cucumber", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "capsicum", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "bell pepper", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "zucchini", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "courgette", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "mushroom", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "mushrooms", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "celery", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "cabbage", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "kale", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "green beans", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "peas", weight: 1, categorySlug: "fruit_veg" },
  { keyword: "corn", weight: 1, categorySlug: "fruit_veg" },
  { keyword: "sweetcorn", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "strawberry", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "strawberries", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "blueberry", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "blueberries", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "raspberry", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "raspberries", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "blackberries", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "grapes", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "watermelon", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "rockmelon", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "cantaloupe", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "pineapple", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "mango", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "mangoes", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "peach", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "peaches", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "nectarine", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "nectarines", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "pear", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "pears", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "kiwi", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "kiwifruit", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "fruit", weight: 1, categorySlug: "fruit_veg" },
  { keyword: "vegetable", weight: 1, categorySlug: "fruit_veg" },
  { keyword: "vegetables", weight: 1, categorySlug: "fruit_veg" },

  // ============================================================
  // HOUSEHOLD ITEMS
  // ============================================================
  { keyword: "laundry detergent", weight: 2, categorySlug: "household_items" },
  { keyword: "laundry powder", weight: 2, categorySlug: "household_items" },
  { keyword: "washing powder", weight: 2, categorySlug: "household_items" },
  { keyword: "washing liquid", weight: 2, categorySlug: "household_items" },
  { keyword: "fabric softener", weight: 2, categorySlug: "household_items" },
  { keyword: "dishwashing liquid", weight: 2, categorySlug: "household_items" },
  { keyword: "dishwashing tablets", weight: 2, categorySlug: "household_items" },
  { keyword: "dishwasher tablets", weight: 2, categorySlug: "household_items" },
  { keyword: "dishwasher detergent", weight: 2, categorySlug: "household_items" },
  { keyword: "dish soap", weight: 2, categorySlug: "household_items" },
  { keyword: "dish liquid", weight: 2, categorySlug: "household_items" },
  { keyword: "paper towels", weight: 2, categorySlug: "household_items" },
  { keyword: "paper towel", weight: 2, categorySlug: "household_items" },
  { keyword: "toilet paper", weight: 2, categorySlug: "household_items" },
  { keyword: "toilet rolls", weight: 2, categorySlug: "household_items" },
  { keyword: "toilet roll", weight: 2, categorySlug: "household_items" },
  { keyword: "kitchen roll", weight: 2, categorySlug: "household_items" },
  { keyword: "tissues", weight: 1, categorySlug: "household_items" },
  { keyword: "facial tissues", weight: 2, categorySlug: "household_items" },
  { keyword: "trash bags", weight: 2, categorySlug: "household_items" },
  { keyword: "garbage bags", weight: 2, categorySlug: "household_items" },
  { keyword: "bin bags", weight: 2, categorySlug: "household_items" },
  { keyword: "bin liners", weight: 2, categorySlug: "household_items" },
  { keyword: "surface cleaner", weight: 2, categorySlug: "household_items" },
  { keyword: "glass cleaner", weight: 2, categorySlug: "household_items" },
  { keyword: "bathroom cleaner", weight: 2, categorySlug: "household_items" },
  { keyword: "toilet cleaner", weight: 2, categorySlug: "household_items" },
  { keyword: "floor cleaner", weight: 2, categorySlug: "household_items" },
  { keyword: "bleach", weight: 2, categorySlug: "household_items" },
  { keyword: "disinfectant", weight: 2, categorySlug: "household_items" },
  { keyword: "sponges", weight: 2, categorySlug: "household_items" },
  { keyword: "sponge", weight: 2, categorySlug: "household_items" },
  { keyword: "scrubbers", weight: 2, categorySlug: "household_items" },
  { keyword: "cleaning spray", weight: 2, categorySlug: "household_items" },
  { keyword: "cleaning wipes", weight: 2, categorySlug: "household_items" },
  { keyword: "disinfectant wipes", weight: 2, categorySlug: "household_items" },
  { keyword: "aluminium foil", weight: 2, categorySlug: "household_items" },
  { keyword: "aluminum foil", weight: 2, categorySlug: "household_items" },
  { keyword: "cling wrap", weight: 2, categorySlug: "household_items" },
  { keyword: "plastic wrap", weight: 2, categorySlug: "household_items" },
  { keyword: "baking paper", weight: 1, categorySlug: "household_items" },
  { keyword: "greaseproof paper", weight: 2, categorySlug: "household_items" },
  { keyword: "batteries", weight: 2, categorySlug: "household_items" },
  { keyword: "battery", weight: 2, categorySlug: "household_items" },
  { keyword: "light bulbs", weight: 2, categorySlug: "household_items" },
  { keyword: "light bulb", weight: 2, categorySlug: "household_items" },
  { keyword: "air freshener", weight: 2, categorySlug: "household_items" },

  // ============================================================
  // MEAT
  // ============================================================
  { keyword: "chicken breast", weight: 2, categorySlug: "meat" },
  { keyword: "chicken breasts", weight: 2, categorySlug: "meat" },
  { keyword: "chicken thigh", weight: 2, categorySlug: "meat" },
  { keyword: "chicken thighs", weight: 2, categorySlug: "meat" },
  { keyword: "chicken drumsticks", weight: 2, categorySlug: "meat" },
  { keyword: "chicken wings", weight: 2, categorySlug: "meat" },
  { keyword: "chicken mince", weight: 2, categorySlug: "meat" },
  { keyword: "chicken fillet", weight: 2, categorySlug: "meat" },
  { keyword: "chicken fillets", weight: 2, categorySlug: "meat" },
  { keyword: "whole chicken", weight: 2, categorySlug: "meat" },
  { keyword: "beef mince", weight: 2, categorySlug: "meat" },
  { keyword: "minced beef", weight: 2, categorySlug: "meat" },
  { keyword: "beef steak", weight: 2, categorySlug: "meat" },
  { keyword: "steak", weight: 2, categorySlug: "meat" },
  { keyword: "rump steak", weight: 2, categorySlug: "meat" },
  { keyword: "sirloin steak", weight: 2, categorySlug: "meat" },
  { keyword: "scotch fillet", weight: 2, categorySlug: "meat" },
  { keyword: "t-bone steak", weight: 2, categorySlug: "meat" },
  { keyword: "beef roast", weight: 2, categorySlug: "meat" },
  { keyword: "roast beef", weight: 1, categorySlug: "meat" },
  { keyword: "pork chops", weight: 2, categorySlug: "meat" },
  { keyword: "pork chop", weight: 2, categorySlug: "meat" },
  { keyword: "pork mince", weight: 2, categorySlug: "meat" },
  { keyword: "pork belly", weight: 2, categorySlug: "meat" },
  { keyword: "pork roast", weight: 2, categorySlug: "meat" },
  { keyword: "lamb chops", weight: 2, categorySlug: "meat" },
  { keyword: "lamb chop", weight: 2, categorySlug: "meat" },
  { keyword: "lamb shanks", weight: 2, categorySlug: "meat" },
  { keyword: "lamb roast", weight: 2, categorySlug: "meat" },
  { keyword: "lamb mince", weight: 2, categorySlug: "meat" },
  { keyword: "bacon", weight: 2, categorySlug: "meat" },
  { keyword: "sausages", weight: 2, categorySlug: "meat" },
  { keyword: "sausage", weight: 2, categorySlug: "meat" },
  { keyword: "beef sausages", weight: 2, categorySlug: "meat" },
  { keyword: "chicken sausages", weight: 2, categorySlug: "meat" },
  { keyword: "lamb sausages", weight: 2, categorySlug: "meat" },
  { keyword: "turkey", weight: 2, categorySlug: "meat" },
  { keyword: "turkey breast", weight: 2, categorySlug: "meat" },
  { keyword: "veal", weight: 2, categorySlug: "meat" },
  { keyword: "veal steaks", weight: 2, categorySlug: "meat" },
  { keyword: "beef ribs", weight: 2, categorySlug: "meat" },
  { keyword: "pork ribs", weight: 2, categorySlug: "meat" },

  // ============================================================
  // COFFEE / TEA
  // ============================================================
  { keyword: "coffee", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "coffee beans", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "ground coffee", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "instant coffee", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "coffee pods", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "coffee capsules", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "espresso coffee", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "decaf coffee", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "decaffeinated coffee", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "coffee grounds", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "tea", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "tea bags", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "black tea", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "green tea", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "herbal tea", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "peppermint tea", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "chai", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "chai tea", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "earl grey", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "english breakfast tea", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "chamomile tea", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "hot chocolate", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "hot chocolate powder", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "drinking chocolate", weight: 2, categorySlug: "coffee_tea" },

  // ============================================================
  // BEVERAGES
  // ============================================================
  { keyword: "bottled water", weight: 2, categorySlug: "beverages" },
  { keyword: "sparkling water", weight: 2, categorySlug: "beverages" },
  { keyword: "mineral water", weight: 2, categorySlug: "beverages" },
  { keyword: "soda water", weight: 2, categorySlug: "beverages" },
  { keyword: "tonic water", weight: 2, categorySlug: "beverages" },
  { keyword: "soft drink", weight: 2, categorySlug: "beverages" },
  { keyword: "soft drinks", weight: 2, categorySlug: "beverages" },
  { keyword: "cola", weight: 2, categorySlug: "beverages" },
  { keyword: "coke", weight: 2, categorySlug: "beverages" },
  { keyword: "lemonade", weight: 2, categorySlug: "beverages" },
  { keyword: "ginger ale", weight: 2, categorySlug: "beverages" },
  { keyword: "fruit juice", weight: 2, categorySlug: "beverages" },
  { keyword: "orange juice", weight: 2, categorySlug: "beverages" },
  { keyword: "apple juice", weight: 2, categorySlug: "beverages" },
  { keyword: "cranberry juice", weight: 2, categorySlug: "beverages" },
  { keyword: "pineapple juice", weight: 2, categorySlug: "beverages" },
  { keyword: "iced tea", weight: 2, categorySlug: "beverages" },
  { keyword: "sports drink", weight: 2, categorySlug: "beverages" },
  { keyword: "energy drink", weight: 2, categorySlug: "beverages" },
  { keyword: "energy drinks", weight: 2, categorySlug: "beverages" },
  { keyword: "cordial", weight: 2, categorySlug: "beverages" },
  { keyword: "squash", weight: 1, categorySlug: "beverages" },
  { keyword: "electrolyte drink", weight: 2, categorySlug: "beverages" },
  { keyword: "coconut water", weight: 2, categorySlug: "beverages" },
  { keyword: "flavoured water", weight: 2, categorySlug: "beverages" },
  { keyword: "flavored water", weight: 2, categorySlug: "beverages" },

  // ============================================================
  // BREADS / CEREALS
  // ============================================================
  { keyword: "bread", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "sliced bread", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "white bread", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "wholemeal bread", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "wholegrain bread", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "multigrain bread", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "sourdough", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "rye bread", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "bagel", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "bagels", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "english muffin", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "english muffins", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "crumpet", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "crumpets", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "croissant", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "croissants", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "breakfast cereal", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "cereal", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "corn flakes", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "cornflakes", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "rice bubbles", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "weet-bix", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "weetbix", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "oats", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "rolled oats", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "porridge", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "muesli", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "granola", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "breakfast bars", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "cereal bars", weight: 2, categorySlug: "breads_cereals" },

  // ============================================================
  // PASTA / RICE / BEANS
  // ============================================================
  { keyword: "pasta", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "spaghetti", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "penne", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "fusilli", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "fettuccine", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "linguine", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "macaroni", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "rigatoni", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "lasagne sheets", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "lasagna sheets", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "rice", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "white rice", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "brown rice", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "basmati rice", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "jasmine rice", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "arborio rice", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "wild rice", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "quinoa", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "couscous", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "bulgur", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "lentils", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "dried lentils", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "dried beans", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "kidney beans", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "black beans", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "chickpeas", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "dried chickpeas", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "split peas", weight: 2, categorySlug: "pasta_rice_beans" },

  // ============================================================
  // CANNED FOODS / SOUPS
  // ============================================================
  { keyword: "canned", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "tinned", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned tomatoes", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "tinned tomatoes", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned tuna", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "tinned tuna", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned salmon", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "tinned salmon", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned beans", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "tinned beans", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "baked beans", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned corn", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned sweetcorn", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned fruit", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned peaches", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned pineapple", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned soup", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "tinned soup", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "soup", weight: 1, categorySlug: "canned_foods_soups" },
  { keyword: "tomato soup", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "chicken soup", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "vegetable soup", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "broth", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "chicken broth", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "beef broth", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "vegetable broth", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "stock", weight: 1, categorySlug: "canned_foods_soups" },
  { keyword: "chicken stock", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "beef stock", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "vegetable stock", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned coconut milk", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "tinned coconut milk", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "canned coconut cream", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "tinned coconut cream", weight: 2, categorySlug: "canned_foods_soups" },

  // ============================================================
  // PERSONAL CARE / HEALTH
  // ============================================================
  { keyword: "shampoo", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "conditioner", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "toothpaste", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "toothbrush", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "mouthwash", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "dental floss", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "floss", weight: 1, categorySlug: "personal_care_health" },
  { keyword: "body wash", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "body soap", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "hand soap", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "hand wash", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "deodorant", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "antiperspirant", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "razors", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "razor", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "shaving cream", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "shaving gel", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "sunscreen", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "sun cream", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "moisturiser", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "moisturizer", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "face wash", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "face cleanser", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "vitamins", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "multivitamins", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "pain reliever", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "painkillers", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "paracetamol", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "ibuprofen", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "bandages", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "bandage", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "band aids", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "bandaids", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "first aid", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "cotton buds", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "cotton swabs", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "sanitary pads", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "tampons", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "shower gel", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "hand sanitiser", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "hand sanitizer", weight: 2, categorySlug: "personal_care_health" },

  // ============================================================
  // PET CARE
  // ============================================================
  { keyword: "dog food", weight: 2, categorySlug: "pet_care" },
  { keyword: "cat food", weight: 2, categorySlug: "pet_care" },
  { keyword: "puppy food", weight: 2, categorySlug: "pet_care" },
  { keyword: "kitten food", weight: 2, categorySlug: "pet_care" },
  { keyword: "pet food", weight: 2, categorySlug: "pet_care" },
  { keyword: "dog treats", weight: 2, categorySlug: "pet_care" },
  { keyword: "cat treats", weight: 2, categorySlug: "pet_care" },
  { keyword: "pet treats", weight: 2, categorySlug: "pet_care" },
  { keyword: "dog biscuits", weight: 2, categorySlug: "pet_care" },
  { keyword: "cat biscuits", weight: 2, categorySlug: "pet_care" },
  { keyword: "cat litter", weight: 2, categorySlug: "pet_care" },
  { keyword: "kitty litter", weight: 2, categorySlug: "pet_care" },
  { keyword: "pet litter", weight: 2, categorySlug: "pet_care" },
  { keyword: "dog toy", weight: 2, categorySlug: "pet_care" },
  { keyword: "dog toys", weight: 2, categorySlug: "pet_care" },
  { keyword: "cat toy", weight: 2, categorySlug: "pet_care" },
  { keyword: "cat toys", weight: 2, categorySlug: "pet_care" },
  { keyword: "pet toy", weight: 2, categorySlug: "pet_care" },
  { keyword: "chew toy", weight: 2, categorySlug: "pet_care" },
  { keyword: "chew toys", weight: 2, categorySlug: "pet_care" },
  { keyword: "flea treatment", weight: 2, categorySlug: "pet_care" },
  { keyword: "flea treatments", weight: 2, categorySlug: "pet_care" },
  { keyword: "pet shampoo", weight: 2, categorySlug: "pet_care" },
  { keyword: "dog shampoo", weight: 2, categorySlug: "pet_care" },
  { keyword: "cat shampoo", weight: 2, categorySlug: "pet_care" },
  { keyword: "pet bedding", weight: 2, categorySlug: "pet_care" },
  { keyword: "dog lead", weight: 2, categorySlug: "pet_care" },
  { keyword: "dog leash", weight: 2, categorySlug: "pet_care" },
  { keyword: "dog collar", weight: 2, categorySlug: "pet_care" },
  { keyword: "cat collar", weight: 2, categorySlug: "pet_care" },

  // ============================================================
  // BAKING ITEMS
  // ============================================================
  { keyword: "flour", weight: 2, categorySlug: "baking_items" },
  { keyword: "plain flour", weight: 2, categorySlug: "baking_items" },
  { keyword: "self raising flour", weight: 2, categorySlug: "baking_items" },
  { keyword: "self-raising flour", weight: 2, categorySlug: "baking_items" },
  { keyword: "bread flour", weight: 2, categorySlug: "baking_items" },
  { keyword: "cake flour", weight: 2, categorySlug: "baking_items" },
  { keyword: "sugar", weight: 2, categorySlug: "baking_items" },
  { keyword: "caster sugar", weight: 2, categorySlug: "baking_items" },
  { keyword: "castor sugar", weight: 2, categorySlug: "baking_items" },
  { keyword: "brown sugar", weight: 2, categorySlug: "baking_items" },
  { keyword: "icing sugar", weight: 2, categorySlug: "baking_items" },
  { keyword: "powdered sugar", weight: 2, categorySlug: "baking_items" },
  { keyword: "baking powder", weight: 2, categorySlug: "baking_items" },
  { keyword: "bicarbonate soda", weight: 2, categorySlug: "baking_items" },
  { keyword: "bicarbonate of soda", weight: 2, categorySlug: "baking_items" },
  { keyword: "baking soda", weight: 2, categorySlug: "baking_items" },
  { keyword: "yeast", weight: 2, categorySlug: "baking_items" },
  { keyword: "dry yeast", weight: 2, categorySlug: "baking_items" },
  { keyword: "vanilla extract", weight: 2, categorySlug: "baking_items" },
  { keyword: "vanilla essence", weight: 2, categorySlug: "baking_items" },
  { keyword: "cocoa powder", weight: 2, categorySlug: "baking_items" },
  { keyword: "chocolate chips", weight: 2, categorySlug: "baking_items" },
  { keyword: "baking chocolate", weight: 2, categorySlug: "baking_items" },
  { keyword: "cake mix", weight: 2, categorySlug: "baking_items" },
  { keyword: "cake mixes", weight: 2, categorySlug: "baking_items" },
  { keyword: "brownie mix", weight: 2, categorySlug: "baking_items" },
  { keyword: "cookie mix", weight: 2, categorySlug: "baking_items" },
  { keyword: "food colouring", weight: 2, categorySlug: "baking_items" },
  { keyword: "food coloring", weight: 2, categorySlug: "baking_items" },
  { keyword: "sprinkles", weight: 2, categorySlug: "baking_items" },
  { keyword: "desiccated coconut", weight: 2, categorySlug: "baking_items" },
  { keyword: "gelatin", weight: 2, categorySlug: "baking_items" },
  { keyword: "gelatine", weight: 2, categorySlug: "baking_items" },

  // ============================================================
  // SPICES / SEASONINGS
  // ============================================================
  { keyword: "salt", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "sea salt", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "rock salt", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "table salt", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "black pepper", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "white pepper", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "pepper", weight: 1, categorySlug: "spices_seasonings" },
  { keyword: "paprika", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "smoked paprika", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "cumin", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "cinnamon", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "oregano", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "basil", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "thyme", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "rosemary", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "sage", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "garlic powder", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "onion powder", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "curry powder", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "chilli flakes", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "chilli powder", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "chili flakes", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "chili powder", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "turmeric", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "nutmeg", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "coriander seeds", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "ground coriander", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "mixed herbs", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "italian herbs", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "seasoning", weight: 1, categorySlug: "spices_seasonings" },
  { keyword: "seasoning mix", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "five spice", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "garam masala", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "cayenne pepper", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "bay leaves", weight: 2, categorySlug: "spices_seasonings" },

  // ============================================================
  // OILS / DRESSINGS
  // ============================================================
  { keyword: "olive oil", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "extra virgin olive oil", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "vegetable oil", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "canola oil", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "sunflower oil", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "avocado oil", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "sesame oil", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "coconut oil", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "peanut oil", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "grapeseed oil", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "balsamic vinegar", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "apple cider vinegar", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "white vinegar", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "red wine vinegar", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "white wine vinegar", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "rice vinegar", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "salad dressing", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "italian dressing", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "ranch dressing", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "caesar dressing", weight: 2, categorySlug: "oils_dressings" },
  { keyword: "vinaigrette", weight: 2, categorySlug: "oils_dressings" },

  // ============================================================
  // WINE / BEER / SPIRITS
  // ============================================================
  { keyword: "beer", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "beers", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "lager", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "ale", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "pale ale", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "ipa", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "stout", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "porter", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "cider", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "hard cider", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "wine", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "red wine", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "white wine", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "rose wine", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "rosé", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "champagne", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "prosecco", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "sparkling wine", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "whiskey", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "whisky", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "bourbon", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "vodka", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "gin", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "rum", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "tequila", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "brandy", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "liqueur", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "liqueurs", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "schnapps", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "seltzer", weight: 2, categorySlug: "wine_beer_spirits" },
  { keyword: "hard seltzer", weight: 2, categorySlug: "wine_beer_spirits" },

  // ============================================================
  // SAUCES / CONDIMENTS
  // ============================================================
  { keyword: "ketchup", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "tomato sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "tomato ketchup", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "mayonnaise", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "mayo", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "mustard", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "dijon mustard", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "bbq sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "barbecue sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "soy sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "hot sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "sweet chilli sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "sweet chili sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "teriyaki sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "oyster sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "fish sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "hoisin sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "pesto", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "peanut butter", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "almond butter", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "jam", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "strawberry jam", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "raspberry jam", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "marmalade", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "honey", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "maple syrup", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "marinade", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "marinades", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "relish", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "chutney", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "apple sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "horseradish sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "tahini", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "sriracha", weight: 2, categorySlug: "sauces_condiments" },

  // ============================================================
  // SNACKS / SWEETS
  // ============================================================
  { keyword: "potato chips", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "potato crisps", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "chips", weight: 1, categorySlug: "snacks_sweets" },
  { keyword: "crisps", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "corn chips", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "tortilla chips", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "pretzels", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "crackers", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "rice crackers", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "chocolate bar", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "chocolate bars", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "chocolate", weight: 1, categorySlug: "snacks_sweets" },
  { keyword: "lollies", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "candy", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "gummy bears", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "gummies", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "jelly beans", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "popcorn", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "mixed nuts", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "cashews", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "almonds", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "peanuts", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "pistachios", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "nuts", weight: 1, categorySlug: "snacks_sweets" },
  { keyword: "cookies", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "biscuits", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "sweet biscuits", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "muesli bars", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "snack bars", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "trail mix", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "marshmallows", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "fudge", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "toffee", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "caramel", weight: 1, categorySlug: "snacks_sweets" },

  // ============================================================
  // DELI
  // ============================================================
  { keyword: "deli", weight: 2, categorySlug: "deli" },
  { keyword: "deli meat", weight: 2, categorySlug: "deli" },
  { keyword: "deli meats", weight: 2, categorySlug: "deli" },
  { keyword: "sliced ham", weight: 2, categorySlug: "deli" },
  { keyword: "sliced salami", weight: 2, categorySlug: "deli" },
  { keyword: "salami", weight: 2, categorySlug: "deli" },
  { keyword: "prosciutto", weight: 2, categorySlug: "deli" },
  { keyword: "mortadella", weight: 2, categorySlug: "deli" },
  { keyword: "pastrami", weight: 2, categorySlug: "deli" },
  { keyword: "sliced roast beef", weight: 2, categorySlug: "deli" },
  { keyword: "cold cuts", weight: 2, categorySlug: "deli" },
  { keyword: "antipasto", weight: 2, categorySlug: "deli" },
  { keyword: "antipasti", weight: 2, categorySlug: "deli" },
  { keyword: "deli olives", weight: 2, categorySlug: "deli" },
  { keyword: "hummus", weight: 2, categorySlug: "deli" },
  { keyword: "deli dip", weight: 2, categorySlug: "deli" },
  { keyword: "tapenade", weight: 2, categorySlug: "deli" },
  { keyword: "specialty cheese", weight: 2, categorySlug: "deli" },
  { keyword: "specialty cheeses", weight: 2, categorySlug: "deli" },
  { keyword: "gourmet cheese", weight: 2, categorySlug: "deli" },
  { keyword: "charcuterie", weight: 2, categorySlug: "deli" },
  { keyword: "pâté", weight: 2, categorySlug: "deli" },
  { keyword: "pate", weight: 2, categorySlug: "deli" },

  // ============================================================
  // SEAFOOD
  // ============================================================
  { keyword: "salmon fillet", weight: 2, categorySlug: "seafood" },
  { keyword: "salmon fillets", weight: 2, categorySlug: "seafood" },
  { keyword: "fresh salmon", weight: 2, categorySlug: "seafood" },
  { keyword: "salmon", weight: 1, categorySlug: "seafood" },
  { keyword: "tuna steak", weight: 2, categorySlug: "seafood" },
  { keyword: "tuna steaks", weight: 2, categorySlug: "seafood" },
  { keyword: "fresh tuna", weight: 2, categorySlug: "seafood" },
  { keyword: "prawns", weight: 2, categorySlug: "seafood" },
  { keyword: "prawn", weight: 2, categorySlug: "seafood" },
  { keyword: "shrimp", weight: 2, categorySlug: "seafood" },
  { keyword: "king prawns", weight: 2, categorySlug: "seafood" },
  { keyword: "calamari", weight: 2, categorySlug: "seafood" },
  { keyword: "squid", weight: 2, categorySlug: "seafood" },
  { keyword: "oysters", weight: 2, categorySlug: "seafood" },
  { keyword: "oyster", weight: 2, categorySlug: "seafood" },
  { keyword: "mussels", weight: 2, categorySlug: "seafood" },
  { keyword: "mussel", weight: 2, categorySlug: "seafood" },
  { keyword: "crab meat", weight: 2, categorySlug: "seafood" },
  { keyword: "crab", weight: 2, categorySlug: "seafood" },
  { keyword: "cod", weight: 2, categorySlug: "seafood" },
  { keyword: "haddock", weight: 2, categorySlug: "seafood" },
  { keyword: "snapper", weight: 2, categorySlug: "seafood" },
  { keyword: "barramundi", weight: 2, categorySlug: "seafood" },
  { keyword: "white fish", weight: 2, categorySlug: "seafood" },
  { keyword: "fish fillet", weight: 2, categorySlug: "seafood" },
  { keyword: "fish fillets", weight: 2, categorySlug: "seafood" },
  { keyword: "fresh fish", weight: 2, categorySlug: "seafood" },
  { keyword: "seafood", weight: 2, categorySlug: "seafood" },
  { keyword: "scallops", weight: 2, categorySlug: "seafood" },
  { keyword: "scallop", weight: 2, categorySlug: "seafood" },
  { keyword: "trout", weight: 2, categorySlug: "seafood" },
  { keyword: "sardines", weight: 2, categorySlug: "seafood" },
  { keyword: "anchovies", weight: 2, categorySlug: "seafood" },

  // ============================================================
  // STATIONERY
  // ============================================================
  { keyword: "pen", weight: 2, categorySlug: "stationery" },
  { keyword: "pens", weight: 2, categorySlug: "stationery" },
  { keyword: "ballpoint pen", weight: 2, categorySlug: "stationery" },
  { keyword: "pencil", weight: 2, categorySlug: "stationery" },
  { keyword: "pencils", weight: 2, categorySlug: "stationery" },
  { keyword: "mechanical pencil", weight: 2, categorySlug: "stationery" },
  { keyword: "notebook", weight: 2, categorySlug: "stationery" },
  { keyword: "notebooks", weight: 2, categorySlug: "stationery" },
  { keyword: "exercise book", weight: 2, categorySlug: "stationery" },
  { keyword: "exercise books", weight: 2, categorySlug: "stationery" },
  { keyword: "sticky notes", weight: 2, categorySlug: "stationery" },
  { keyword: "post it notes", weight: 2, categorySlug: "stationery" },
  { keyword: "markers", weight: 2, categorySlug: "stationery" },
  { keyword: "marker", weight: 2, categorySlug: "stationery" },
  { keyword: "highlighter", weight: 2, categorySlug: "stationery" },
  { keyword: "highlighters", weight: 2, categorySlug: "stationery" },
  { keyword: "envelopes", weight: 2, categorySlug: "stationery" },
  { keyword: "envelope", weight: 2, categorySlug: "stationery" },
  { keyword: "sticky tape", weight: 2, categorySlug: "stationery" },
  { keyword: "tape", weight: 1, categorySlug: "stationery" },
  { keyword: "glue stick", weight: 2, categorySlug: "stationery" },
  { keyword: "glue sticks", weight: 2, categorySlug: "stationery" },
  { keyword: "glue", weight: 1, categorySlug: "stationery" },
  { keyword: "rubber", weight: 2, categorySlug: "stationery" },
  { keyword: "eraser", weight: 2, categorySlug: "stationery" },
  { keyword: "ruler", weight: 2, categorySlug: "stationery" },
  { keyword: "rulers", weight: 2, categorySlug: "stationery" },
  { keyword: "scissors", weight: 2, categorySlug: "stationery" },
  { keyword: "stapler", weight: 2, categorySlug: "stationery" },
  { keyword: "staples", weight: 2, categorySlug: "stationery" },
  { keyword: "printer paper", weight: 2, categorySlug: "stationery" },
  { keyword: "copy paper", weight: 2, categorySlug: "stationery" },
  { keyword: "paper", weight: 1, categorySlug: "stationery" },
  { keyword: "folders", weight: 2, categorySlug: "stationery" },
  { keyword: "folder", weight: 2, categorySlug: "stationery" },
  { keyword: "binder", weight: 2, categorySlug: "stationery" },
  { keyword: "binders", weight: 2, categorySlug: "stationery" },
  { keyword: "school supplies", weight: 2, categorySlug: "stationery" },
  { keyword: "stationery", weight: 2, categorySlug: "stationery" },
];
