export const categories = [
  {
    name: "frozen_foods",
    displayName: "Frozen Foods",
  },
  {
    name: "dairy_eggs_cheese",
    displayName: "Dairy, Eggs & Cheese",
  },
  {
    name: "fruit_veg",
    displayName: "Fruit & Veg",
  },
  {
    name: "household_items",
    displayName: "Household Items",
  },
  {
    name: "meat",
    displayName: "Meat",
  },
  {
    name: "coffee_tea",
    displayName: "Coffee & Tea",
  },
  {
    name: "beverages",
    displayName: "Beverages",
  },
  {
    name: "breads_cereals",
    displayName: "Bread & Cereals",
  },
  {
    name: "pasta_rice_beans",
    displayName: "Pasta, Rice & Beans",
  },
  {
    name: "canned_foods_soups",
    displayName: "Canned Foods & Soups",
  },
  {
    name: "personal_care_health",
    displayName: "Personal Care & Health",
  },
  {
    name: "pet_care",
    displayName: "Pet Care",
  },
  {
    name: "baking_items",
    displayName: "Baking Items",
  },
  {
    name: "spices_seasonings",
    displayName: "Spices & Seasonings",
  },
  {
    name: "oils_dressings",
    displayName: "Oils & Dressings",
  },
  {
    name: "wine_beer_spirits",
    displayName: "Wine, Beer & Spirits",
  },
  {
    name: "sauces_condiments",
    displayName: "Sauces & Condiments",
  },
  {
    name: "snacks_sweets",
    displayName: "Snacks & Sweets",
  },
  {
    name: "deli",
    displayName: "Deli",
  },
  {
    name: "seafood",
    displayName: "Seafood",
  },
  {
    name: "stationery",
    displayName: "Stationery",
  },
];

export const categoryKeywords = [
  // ============================================================
  // FROZEN FOODS
  // ============================================================

  { keyword: "frozen", weight: 3, categoryId: 1 },
  { keyword: "frozen food", weight: 3, categoryId: 1 },
  { keyword: "frozen meal", weight: 3, categoryId: 1 },
  { keyword: "frozen meals", weight: 3, categoryId: 1 },
  { keyword: "frozen pizza", weight: 3, categoryId: 1 },
  { keyword: "frozen chips", weight: 3, categoryId: 1 },
  { keyword: "frozen fries", weight: 3, categoryId: 1 },
  { keyword: "frozen vegetables", weight: 3, categoryId: 1 },
  { keyword: "frozen veg", weight: 3, categoryId: 1 },
  { keyword: "frozen berries", weight: 3, categoryId: 1 },
  { keyword: "frozen fruit", weight: 3, categoryId: 1 },
  { keyword: "frozen pastry", weight: 3, categoryId: 1 },
  { keyword: "frozen dessert", weight: 3, categoryId: 1 },
  { keyword: "frozen desserts", weight: 3, categoryId: 1 },
  { keyword: "ice cream", weight: 3, categoryId: 1 },
  { keyword: "icecream", weight: 3, categoryId: 1 },
  { keyword: "gelato", weight: 3, categoryId: 1 },
  { keyword: "sorbet", weight: 3, categoryId: 1 },
  { keyword: "frozen fish", weight: 2, categoryId: 1 },
  { keyword: "frozen chicken", weight: 2, categoryId: 1 },
  { keyword: "frozen nuggets", weight: 3, categoryId: 1 },
  { keyword: "chicken nuggets", weight: 2, categoryId: 1 },
  { keyword: "frozen chips", weight: 3, categoryId: 1 },
  { keyword: "hash browns", weight: 3, categoryId: 1 },
  { keyword: "frozen hash browns", weight: 3, categoryId: 1 },
  { keyword: "frozen peas", weight: 3, categoryId: 1 },
  { keyword: "frozen corn", weight: 3, categoryId: 1 },
  { keyword: "frozen spinach", weight: 3, categoryId: 1 },
  { keyword: "frozen berries", weight: 3, categoryId: 1 },
  { keyword: "frozen dumplings", weight: 3, categoryId: 1 },
  { keyword: "frozen spring rolls", weight: 3, categoryId: 1 },
  { keyword: "frozen waffles", weight: 3, categoryId: 1 },
  { keyword: "frozen pancakes", weight: 3, categoryId: 1 },
  { keyword: "frozen pie", weight: 3, categoryId: 1 },
  { keyword: "frozen sausage rolls", weight: 3, categoryId: 1 },
  { keyword: "frozen garlic bread", weight: 3, categoryId: 1 },

  // ============================================================
  // DAIRY, EGGS & CHEESE
  // ============================================================

  { keyword: "milk", weight: 3, categoryId: 2 },
  { keyword: "full cream milk", weight: 3, categoryId: 2 },
  { keyword: "full cream", weight: 2, categoryId: 2 },
  { keyword: "skim milk", weight: 3, categoryId: 2 },
  { keyword: "low fat milk", weight: 3, categoryId: 2 },
  { keyword: "long life milk", weight: 3, categoryId: 2 },
  { keyword: "uht milk", weight: 3, categoryId: 2 },
  { keyword: "soy milk", weight: 2, categoryId: 2 },
  { keyword: "oat milk", weight: 2, categoryId: 2 },
  { keyword: "almond milk", weight: 2, categoryId: 2 },
  { keyword: "coconut milk", weight: 1, categoryId: 2 },
  { keyword: "eggs", weight: 3, categoryId: 2 },
  { keyword: "egg", weight: 3, categoryId: 2 },
  { keyword: "free range eggs", weight: 3, categoryId: 2 },
  { keyword: "butter", weight: 3, categoryId: 2 },
  { keyword: "margarine", weight: 3, categoryId: 2 },
  { keyword: "spreadable butter", weight: 3, categoryId: 2 },
  { keyword: "cheese", weight: 3, categoryId: 2 },
  { keyword: "cheddar", weight: 3, categoryId: 2 },
  { keyword: "tasty cheese", weight: 3, categoryId: 2 },
  { keyword: "mozzarella", weight: 3, categoryId: 2 },
  { keyword: "parmesan", weight: 3, categoryId: 2 },
  { keyword: "parmesan cheese", weight: 3, categoryId: 2 },
  { keyword: "feta", weight: 3, categoryId: 2 },
  { keyword: "halloumi", weight: 3, categoryId: 2 },
  { keyword: "cream", weight: 2, categoryId: 2 },
  { keyword: "thickened cream", weight: 3, categoryId: 2 },
  { keyword: "sour cream", weight: 3, categoryId: 2 },
  { keyword: "cottage cheese", weight: 3, categoryId: 2 },
  { keyword: "ricotta", weight: 3, categoryId: 2 },
  { keyword: "cream cheese", weight: 3, categoryId: 2 },
  { keyword: "yoghurt", weight: 3, categoryId: 2 },
  { keyword: "yogurt", weight: 3, categoryId: 2 },
  { keyword: "greek yoghurt", weight: 3, categoryId: 2 },
  { keyword: "custard", weight: 2, categoryId: 2 },

  // ============================================================
  // FRUIT & VEG
  // ============================================================

  { keyword: "fruit", weight: 2, categoryId: 3 },
  { keyword: "vegetable", weight: 2, categoryId: 3 },
  { keyword: "vegetables", weight: 2, categoryId: 3 },
  { keyword: "veg", weight: 2, categoryId: 3 },
  { keyword: "apples", weight: 3, categoryId: 3 },
  { keyword: "apple", weight: 3, categoryId: 3 },
  { keyword: "bananas", weight: 3, categoryId: 3 },
  { keyword: "banana", weight: 3, categoryId: 3 },
  { keyword: "oranges", weight: 3, categoryId: 3 },
  { keyword: "orange", weight: 3, categoryId: 3 },
  { keyword: "mandarins", weight: 3, categoryId: 3 },
  { keyword: "lemons", weight: 3, categoryId: 3 },
  { keyword: "lemon", weight: 3, categoryId: 3 },
  { keyword: "limes", weight: 3, categoryId: 3 },
  { keyword: "lime", weight: 3, categoryId: 3 },
  { keyword: "grapes", weight: 3, categoryId: 3 },
  { keyword: "grape", weight: 3, categoryId: 3 },
  { keyword: "strawberries", weight: 3, categoryId: 3 },
  { keyword: "strawberry", weight: 3, categoryId: 3 },
  { keyword: "blueberries", weight: 3, categoryId: 3 },
  { keyword: "raspberries", weight: 3, categoryId: 3 },
  { keyword: "avocado", weight: 3, categoryId: 3 },
  { keyword: "avocados", weight: 3, categoryId: 3 },
  { keyword: "tomatoes", weight: 3, categoryId: 3 },
  { keyword: "tomato", weight: 3, categoryId: 3 },
  { keyword: "potatoes", weight: 3, categoryId: 3 },
  { keyword: "potato", weight: 3, categoryId: 3 },
  { keyword: "sweet potato", weight: 3, categoryId: 3 },
  { keyword: "carrots", weight: 3, categoryId: 3 },
  { keyword: "carrot", weight: 3, categoryId: 3 },
  { keyword: "onions", weight: 3, categoryId: 3 },
  { keyword: "onion", weight: 3, categoryId: 3 },
  { keyword: "garlic", weight: 3, categoryId: 3 },
  { keyword: "broccoli", weight: 3, categoryId: 3 },
  { keyword: "cauliflower", weight: 3, categoryId: 3 },
  { keyword: "spinach", weight: 3, categoryId: 3 },
  { keyword: "lettuce", weight: 3, categoryId: 3 },
  { keyword: "cucumber", weight: 3, categoryId: 3 },
  { keyword: "capsicum", weight: 3, categoryId: 3 },
  { keyword: "bell pepper", weight: 3, categoryId: 3 },
  { keyword: "zucchini", weight: 3, categoryId: 3 },
  { keyword: "courgette", weight: 3, categoryId: 3 },
  { keyword: "eggplant", weight: 3, categoryId: 3 },
  { keyword: "aubergine", weight: 3, categoryId: 3 },
  { keyword: "mushrooms", weight: 3, categoryId: 3 },
  { keyword: "mushroom", weight: 3, categoryId: 3 },
  { keyword: "celery", weight: 3, categoryId: 3 },
  { keyword: "cabbage", weight: 3, categoryId: 3 },
  { keyword: "beans", weight: 2, categoryId: 3 },
  { keyword: "green beans", weight: 3, categoryId: 3 },
  { keyword: "spring onions", weight: 3, categoryId: 3 },
  { keyword: "leek", weight: 3, categoryId: 3 },
  { keyword: "pumpkin", weight: 3, categoryId: 3 },
  { keyword: "corn", weight: 2, categoryId: 3 },

  // ============================================================
  // HOUSEHOLD ITEMS
  // ============================================================

  { keyword: "laundry detergent", weight: 3, categoryId: 4 },
  { keyword: "laundry powder", weight: 3, categoryId: 4 },
  { keyword: "washing powder", weight: 3, categoryId: 4 },
  { keyword: "washing liquid", weight: 3, categoryId: 4 },
  { keyword: "fabric softener", weight: 3, categoryId: 4 },
  { keyword: "dishwashing liquid", weight: 3, categoryId: 4 },
  { keyword: "dish soap", weight: 3, categoryId: 4 },
  { keyword: "dishwasher tablets", weight: 3, categoryId: 4 },
  { keyword: "dishwasher powder", weight: 3, categoryId: 4 },
  { keyword: "surface cleaner", weight: 3, categoryId: 4 },
  { keyword: "glass cleaner", weight: 3, categoryId: 4 },
  { keyword: "window cleaner", weight: 3, categoryId: 4 },
  { keyword: "floor cleaner", weight: 3, categoryId: 4 },
  { keyword: "disinfectant", weight: 3, categoryId: 4 },
  { keyword: "bleach", weight: 3, categoryId: 4 },
  { keyword: "sponges", weight: 3, categoryId: 4 },
  { keyword: "sponge", weight: 3, categoryId: 4 },
  { keyword: "scrubbers", weight: 3, categoryId: 4 },
  { keyword: "paper towels", weight: 3, categoryId: 4 },
  { keyword: "paper towel", weight: 3, categoryId: 4 },
  { keyword: "toilet paper", weight: 3, categoryId: 4 },
  { keyword: "toilet rolls", weight: 3, categoryId: 4 },
  { keyword: "tissues", weight: 3, categoryId: 4 },
  { keyword: "facial tissues", weight: 3, categoryId: 4 },
  { keyword: "bin bags", weight: 3, categoryId: 4 },
  { keyword: "bin liners", weight: 3, categoryId: 4 },
  { keyword: "garbage bags", weight: 3, categoryId: 4 },
  { keyword: "trash bags", weight: 3, categoryId: 4 },
  { keyword: "aluminium foil", weight: 3, categoryId: 4 },
  { keyword: "aluminum foil", weight: 3, categoryId: 4 },
  { keyword: "cling wrap", weight: 3, categoryId: 4 },
  { keyword: "plastic wrap", weight: 3, categoryId: 4 },
  { keyword: "baking paper", weight: 2, categoryId: 4 },
  { keyword: "food storage bags", weight: 3, categoryId: 4 },
  { keyword: "batteries", weight: 3, categoryId: 4 },
  { keyword: "light bulbs", weight: 3, categoryId: 4 },
  { keyword: "air freshener", weight: 3, categoryId: 4 },

  // ============================================================
  // MEAT
  // ============================================================

  { keyword: "meat", weight: 3, categoryId: 5 },
  { keyword: "chicken", weight: 3, categoryId: 5 },
  { keyword: "chicken breast", weight: 3, categoryId: 5 },
  { keyword: "chicken thigh", weight: 3, categoryId: 5 },
  { keyword: "chicken thighs", weight: 3, categoryId: 5 },
  { keyword: "chicken drumsticks", weight: 3, categoryId: 5 },
  { keyword: "chicken wings", weight: 3, categoryId: 5 },
  { keyword: "whole chicken", weight: 3, categoryId: 5 },
  { keyword: "beef", weight: 3, categoryId: 5 },
  { keyword: "mince", weight: 2, categoryId: 5 },
  { keyword: "beef mince", weight: 3, categoryId: 5 },
  { keyword: "minced beef", weight: 3, categoryId: 5 },
  { keyword: "steak", weight: 3, categoryId: 5 },
  { keyword: "rump steak", weight: 3, categoryId: 5 },
  { keyword: "scotch fillet", weight: 3, categoryId: 5 },
  { keyword: "sirloin", weight: 3, categoryId: 5 },
  { keyword: "beef roast", weight: 3, categoryId: 5 },
  { keyword: "beef brisket", weight: 3, categoryId: 5 },
  { keyword: "pork", weight: 3, categoryId: 5 },
  { keyword: "pork chops", weight: 3, categoryId: 5 },
  { keyword: "pork belly", weight: 3, categoryId: 5 },
  { keyword: "pork loin", weight: 3, categoryId: 5 },
  { keyword: "lamb", weight: 3, categoryId: 5 },
  { keyword: "lamb chops", weight: 3, categoryId: 5 },
  { keyword: "lamb shanks", weight: 3, categoryId: 5 },
  { keyword: "lamb roast", weight: 3, categoryId: 5 },
  { keyword: "bacon", weight: 3, categoryId: 5 },
  { keyword: "sausages", weight: 3, categoryId: 5 },
  { keyword: "sausage", weight: 3, categoryId: 5 },
  { keyword: "bratwurst", weight: 3, categoryId: 5 },
  { keyword: "chorizo", weight: 3, categoryId: 5 },
  { keyword: "turkey", weight: 3, categoryId: 5 },
  { keyword: "veal", weight: 3, categoryId: 5 },
  { keyword: "ham", weight: 2, categoryId: 5 },
  { keyword: "roast beef", weight: 2, categoryId: 5 },

  // ============================================================
  // COFFEE & TEA
  // ============================================================

  { keyword: "coffee", weight: 3, categoryId: 6 },
  { keyword: "coffee beans", weight: 3, categoryId: 6 },
  { keyword: "ground coffee", weight: 3, categoryId: 6 },
  { keyword: "instant coffee", weight: 3, categoryId: 6 },
  { keyword: "coffee pods", weight: 3, categoryId: 6 },
  { keyword: "coffee capsules", weight: 3, categoryId: 6 },
  { keyword: "espresso", weight: 2, categoryId: 6 },
  { keyword: "decaf coffee", weight: 3, categoryId: 6 },
  { keyword: "tea", weight: 3, categoryId: 6 },
  { keyword: "tea bags", weight: 3, categoryId: 6 },
  { keyword: "black tea", weight: 3, categoryId: 6 },
  { keyword: "green tea", weight: 3, categoryId: 6 },
  { keyword: "herbal tea", weight: 3, categoryId: 6 },
  { keyword: "peppermint tea", weight: 3, categoryId: 6 },
  { keyword: "chai", weight: 3, categoryId: 6 },
  { keyword: "chai tea", weight: 3, categoryId: 6 },
  { keyword: "earl grey", weight: 3, categoryId: 6 },
  { keyword: "english breakfast tea", weight: 3, categoryId: 6 },
  { keyword: "matcha", weight: 3, categoryId: 6 },
  { keyword: "hot chocolate", weight: 3, categoryId: 6 },
  { keyword: "hot chocolate powder", weight: 3, categoryId: 6 },
  { keyword: "cocoa drink", weight: 2, categoryId: 6 },

  // ============================================================
  // BEVERAGES
  // ============================================================

  { keyword: "water", weight: 2, categoryId: 7 },
  { keyword: "bottled water", weight: 3, categoryId: 7 },
  { keyword: "sparkling water", weight: 3, categoryId: 7 },
  { keyword: "mineral water", weight: 3, categoryId: 7 },
  { keyword: "soda", weight: 3, categoryId: 7 },
  { keyword: "soft drink", weight: 3, categoryId: 7 },
  { keyword: "soft drinks", weight: 3, categoryId: 7 },
  { keyword: "coke", weight: 3, categoryId: 7 },
  { keyword: "cola", weight: 3, categoryId: 7 },
  { keyword: "lemonade", weight: 3, categoryId: 7 },
  { keyword: "ginger beer", weight: 3, categoryId: 7 },
  { keyword: "fruit juice", weight: 3, categoryId: 7 },
  { keyword: "orange juice", weight: 3, categoryId: 7 },
  { keyword: "apple juice", weight: 3, categoryId: 7 },
  { keyword: "cranberry juice", weight: 3, categoryId: 7 },
  { keyword: "iced tea", weight: 3, categoryId: 7 },
  { keyword: "sports drink", weight: 3, categoryId: 7 },
  { keyword: "energy drink", weight: 3, categoryId: 7 },
  { keyword: "energy drinks", weight: 3, categoryId: 7 },
  { keyword: "cordial", weight: 3, categoryId: 7 },
  { keyword: "squash", weight: 2, categoryId: 7 },
  { keyword: "electrolyte drink", weight: 3, categoryId: 7 },
  { keyword: "iced coffee", weight: 2, categoryId: 7 },
  { keyword: "kombucha", weight: 3, categoryId: 7 },

  // ============================================================
  // BREAD & CEREALS
  // ============================================================

  { keyword: "bread", weight: 3, categoryId: 8 },
  { keyword: "white bread", weight: 3, categoryId: 8 },
  { keyword: "wholemeal bread", weight: 3, categoryId: 8 },
  { keyword: "wholegrain bread", weight: 3, categoryId: 8 },
  { keyword: "sourdough", weight: 3, categoryId: 8 },
  { keyword: "rye bread", weight: 3, categoryId: 8 },
  { keyword: "multigrain bread", weight: 3, categoryId: 8 },
  { keyword: "toast", weight: 1, categoryId: 8 },
  { keyword: "toast bread", weight: 2, categoryId: 8 },
  { keyword: "bagels", weight: 3, categoryId: 8 },
  { keyword: "bagel", weight: 3, categoryId: 8 },
  { keyword: "english muffins", weight: 3, categoryId: 8 },
  { keyword: "crumpets", weight: 3, categoryId: 8 },
  { keyword: "wraps", weight: 2, categoryId: 8 },
  { keyword: "tortilla wraps", weight: 3, categoryId: 8 },
  { keyword: "pita bread", weight: 3, categoryId: 8 },
  { keyword: "cereal", weight: 3, categoryId: 8 },
  { keyword: "breakfast cereal", weight: 3, categoryId: 8 },
  { keyword: "corn flakes", weight: 3, categoryId: 8 },
  { keyword: "rice bubbles", weight: 3, categoryId: 8 },
  { keyword: "weetbix", weight: 3, categoryId: 8 },
  { keyword: "muesli", weight: 3, categoryId: 8 },
  { keyword: "granola", weight: 3, categoryId: 8 },
  { keyword: "oats", weight: 3, categoryId: 8 },
  { keyword: "rolled oats", weight: 3, categoryId: 8 },
  { keyword: "porridge", weight: 3, categoryId: 8 },
  { keyword: "breakfast bars", weight: 2, categoryId: 8 },

  // ============================================================
  // PASTA, RICE & BEANS
  // ============================================================

  { keyword: "pasta", weight: 3, categoryId: 9 },
  { keyword: "spaghetti", weight: 3, categoryId: 9 },
  { keyword: "penne", weight: 3, categoryId: 9 },
  { keyword: "fusilli", weight: 3, categoryId: 9 },
  { keyword: "fettuccine", weight: 3, categoryId: 9 },
  { keyword: "linguine", weight: 3, categoryId: 9 },
  { keyword: "macaroni", weight: 3, categoryId: 9 },
  { keyword: "lasagne sheets", weight: 3, categoryId: 9 },
  { keyword: "orzo", weight: 3, categoryId: 9 },
  { keyword: "rice", weight: 3, categoryId: 9 },
  { keyword: "white rice", weight: 3, categoryId: 9 },
  { keyword: "brown rice", weight: 3, categoryId: 9 },
  { keyword: "basmati rice", weight: 3, categoryId: 9 },
  { keyword: "jasmine rice", weight: 3, categoryId: 9 },
  { keyword: "arborio rice", weight: 3, categoryId: 9 },
  { keyword: "wild rice", weight: 3, categoryId: 9 },
  { keyword: "quinoa", weight: 3, categoryId: 9 },
  { keyword: "couscous", weight: 3, categoryId: 9 },
  { keyword: "lentils", weight: 3, categoryId: 9 },
  { keyword: "red lentils", weight: 3, categoryId: 9 },
  { keyword: "green lentils", weight: 3, categoryId: 9 },
  { keyword: "dried beans", weight: 3, categoryId: 9 },
  { keyword: "kidney beans", weight: 3, categoryId: 9 },
  { keyword: "black beans", weight: 3, categoryId: 9 },
  { keyword: "dried chickpeas", weight: 3, categoryId: 9 },
  { keyword: "chickpeas", weight: 2, categoryId: 9 },
  { keyword: "garbanzo beans", weight: 3, categoryId: 9 },

  // ============================================================
  // CANNED FOODS & SOUPS
  // ============================================================

  { keyword: "canned", weight: 3, categoryId: 10 },
  { keyword: "tinned", weight: 3, categoryId: 10 },
  { keyword: "tin", weight: 2, categoryId: 10 },
  { keyword: "canned tomatoes", weight: 3, categoryId: 10 },
  { keyword: "tinned tomatoes", weight: 3, categoryId: 10 },
  { keyword: "crushed tomatoes", weight: 2, categoryId: 10 },
  { keyword: "diced tomatoes", weight: 2, categoryId: 10 },
  { keyword: "tomato paste", weight: 2, categoryId: 10 },
  { keyword: "canned tuna", weight: 3, categoryId: 10 },
  { keyword: "tinned tuna", weight: 3, categoryId: 10 },
  { keyword: "canned salmon", weight: 3, categoryId: 10 },
  { keyword: "canned corn", weight: 3, categoryId: 10 },
  { keyword: "canned beans", weight: 3, categoryId: 10 },
  { keyword: "baked beans", weight: 3, categoryId: 10 },
  { keyword: "canned chickpeas", weight: 3, categoryId: 10 },
  { keyword: "canned lentils", weight: 3, categoryId: 10 },
  { keyword: "canned fruit", weight: 3, categoryId: 10 },
  { keyword: "canned peaches", weight: 3, categoryId: 10 },
  { keyword: "canned pineapple", weight: 3, categoryId: 10 },
  { keyword: "coconut milk", weight: 3, categoryId: 10 },
  { keyword: "coconut cream", weight: 3, categoryId: 10 },
  { keyword: "canned soup", weight: 3, categoryId: 10 },
  { keyword: "tinned soup", weight: 3, categoryId: 10 },
  { keyword: "soup", weight: 2, categoryId: 10 },
  { keyword: "broth", weight: 2, categoryId: 10 },
  { keyword: "stock", weight: 2, categoryId: 10 },
  { keyword: "chicken stock", weight: 2, categoryId: 10 },
  { keyword: "beef stock", weight: 2, categoryId: 10 },
  { keyword: "vegetable stock", weight: 2, categoryId: 10 },

  // ============================================================
  // PERSONAL CARE & HEALTH
  // ============================================================

  { keyword: "shampoo", weight: 3, categoryId: 11 },
  { keyword: "conditioner", weight: 3, categoryId: 11 },
  { keyword: "hair conditioner", weight: 3, categoryId: 11 },
  { keyword: "body wash", weight: 3, categoryId: 11 },
  { keyword: "shower gel", weight: 3, categoryId: 11 },
  { keyword: "soap", weight: 3, categoryId: 11 },
  { keyword: "hand soap", weight: 3, categoryId: 11 },
  { keyword: "hand wash", weight: 3, categoryId: 11 },
  { keyword: "toothpaste", weight: 3, categoryId: 11 },
  { keyword: "toothbrush", weight: 3, categoryId: 11 },
  { keyword: "mouthwash", weight: 3, categoryId: 11 },
  { keyword: "floss", weight: 3, categoryId: 11 },
  { keyword: "deodorant", weight: 3, categoryId: 11 },
  { keyword: "antiperspirant", weight: 3, categoryId: 11 },
  { keyword: "razors", weight: 3, categoryId: 11 },
  { keyword: "shaving cream", weight: 3, categoryId: 11 },
  { keyword: "sunscreen", weight: 3, categoryId: 11 },
  { keyword: "sun cream", weight: 3, categoryId: 11 },
  { keyword: "moisturiser", weight: 3, categoryId: 11 },
  { keyword: "moisturizer", weight: 3, categoryId: 11 },
  { keyword: "lip balm", weight: 3, categoryId: 11 },
  { keyword: "vitamins", weight: 3, categoryId: 11 },
  { keyword: "vitamin", weight: 3, categoryId: 11 },
  { keyword: "pain relief", weight: 3, categoryId: 11 },
  { keyword: "pain reliever", weight: 3, categoryId: 11 },
  { keyword: "paracetamol", weight: 3, categoryId: 11 },
  { keyword: "ibuprofen", weight: 3, categoryId: 11 },
  { keyword: "bandages", weight: 3, categoryId: 11 },
  { keyword: "band aids", weight: 3, categoryId: 11 },
  { keyword: "first aid", weight: 3, categoryId: 11 },
  { keyword: "cotton buds", weight: 3, categoryId: 11 },
  { keyword: "cotton pads", weight: 3, categoryId: 11 },
  { keyword: "tissues", weight: 1, categoryId: 11 },

  // ============================================================
  // PET CARE
  // ============================================================

  { keyword: "pet food", weight: 3, categoryId: 12 },
  { keyword: "dog food", weight: 3, categoryId: 12 },
  { keyword: "cat food", weight: 3, categoryId: 12 },
  { keyword: "puppy food", weight: 3, categoryId: 12 },
  { keyword: "kitten food", weight: 3, categoryId: 12 },
  { keyword: "dog treats", weight: 3, categoryId: 12 },
  { keyword: "cat treats", weight: 3, categoryId: 12 },
  { keyword: "pet treats", weight: 3, categoryId: 12 },
  { keyword: "dog biscuits", weight: 3, categoryId: 12 },
  { keyword: "dog chews", weight: 3, categoryId: 12 },
  { keyword: "dog chew", weight: 3, categoryId: 12 },
  { keyword: "cat litter", weight: 3, categoryId: 12 },
  { keyword: "kitty litter", weight: 3, categoryId: 12 },
  { keyword: "pet shampoo", weight: 3, categoryId: 12 },
  { keyword: "dog shampoo", weight: 3, categoryId: 12 },
  { keyword: "flea treatment", weight: 3, categoryId: 12 },
  { keyword: "flea treatments", weight: 3, categoryId: 12 },
  { keyword: "worming tablets", weight: 3, categoryId: 12 },
  { keyword: "pet toys", weight: 3, categoryId: 12 },
  { keyword: "dog toys", weight: 3, categoryId: 12 },
  { keyword: "cat toys", weight: 3, categoryId: 12 },
  { keyword: "bird seed", weight: 3, categoryId: 12 },
  { keyword: "fish food", weight: 3, categoryId: 12 },
  { keyword: "pet bedding", weight: 3, categoryId: 12 },

  // ============================================================
  // BAKING ITEMS
  // ============================================================

  { keyword: "baking", weight: 2, categoryId: 13 },
  { keyword: "plain flour", weight: 3, categoryId: 13 },
  { keyword: "self raising flour", weight: 3, categoryId: 13 },
  { keyword: "self raising flour", weight: 3, categoryId: 13 },
  { keyword: "flour", weight: 3, categoryId: 13 },
  { keyword: "bread flour", weight: 3, categoryId: 13 },
  { keyword: "baking flour", weight: 3, categoryId: 13 },
  { keyword: "caster sugar", weight: 3, categoryId: 13 },
  { keyword: "icing sugar", weight: 3, categoryId: 13 },
  { keyword: "powdered sugar", weight: 3, categoryId: 13 },
  { keyword: "brown sugar", weight: 3, categoryId: 13 },
  { keyword: "raw sugar", weight: 3, categoryId: 13 },
  { keyword: "baking powder", weight: 3, categoryId: 13 },
  { keyword: "baking soda", weight: 3, categoryId: 13 },
  { keyword: "bicarbonate soda", weight: 3, categoryId: 13 },
  { keyword: "bicarbonate of soda", weight: 3, categoryId: 13 },
  { keyword: "yeast", weight: 3, categoryId: 13 },
  { keyword: "vanilla extract", weight: 3, categoryId: 13 },
  { keyword: "vanilla essence", weight: 3, categoryId: 13 },
  { keyword: "cocoa powder", weight: 3, categoryId: 13 },
  { keyword: "cacao powder", weight: 3, categoryId: 13 },
  { keyword: "chocolate chips", weight: 3, categoryId: 13 },
  { keyword: "baking chocolate", weight: 3, categoryId: 13 },
  { keyword: "cake mix", weight: 3, categoryId: 13 },
  { keyword: "cake mixes", weight: 3, categoryId: 13 },
  { keyword: "brownie mix", weight: 3, categoryId: 13 },
  { keyword: "sprinkles", weight: 3, categoryId: 13 },
  { keyword: "food colouring", weight: 3, categoryId: 13 },
  { keyword: "food coloring", weight: 3, categoryId: 13 },
  { keyword: "gelatine", weight: 3, categoryId: 13 },
  { keyword: "gelatin", weight: 3, categoryId: 13 },
  { keyword: "dessert mix", weight: 2, categoryId: 13 },

  // ============================================================
  // SPICES & SEASONINGS
  // ============================================================

  { keyword: "spice", weight: 3, categoryId: 14 },
  { keyword: "spices", weight: 3, categoryId: 14 },
  { keyword: "seasoning", weight: 3, categoryId: 14 },
  { keyword: "seasonings", weight: 3, categoryId: 14 },
  { keyword: "salt", weight: 3, categoryId: 14 },
  { keyword: "sea salt", weight: 3, categoryId: 14 },
  { keyword: "rock salt", weight: 3, categoryId: 14 },
  { keyword: "black pepper", weight: 3, categoryId: 14 },
  { keyword: "pepper", weight: 2, categoryId: 14 },
  { keyword: "paprika", weight: 3, categoryId: 14 },
  { keyword: "smoked paprika", weight: 3, categoryId: 14 },
  { keyword: "cumin", weight: 3, categoryId: 14 },
  { keyword: "cinnamon", weight: 3, categoryId: 14 },
  { keyword: "oregano", weight: 3, categoryId: 14 },
  { keyword: "thyme", weight: 3, categoryId: 14 },
  { keyword: "rosemary", weight: 3, categoryId: 14 },
  { keyword: "basil", weight: 2, categoryId: 14 },
  { keyword: "dried basil", weight: 3, categoryId: 14 },
  { keyword: "chilli", weight: 2, categoryId: 14 },
  { keyword: "chilli flakes", weight: 3, categoryId: 14 },
  { keyword: "chilli powder", weight: 3, categoryId: 14 },
  { keyword: "curry powder", weight: 3, categoryId: 14 },
  { keyword: "turmeric", weight: 3, categoryId: 14 },
  { keyword: "garlic powder", weight: 3, categoryId: 14 },
  { keyword: "onion powder", weight: 3, categoryId: 14 },
  { keyword: "nutmeg", weight: 3, categoryId: 14 },
  { keyword: "cloves", weight: 2, categoryId: 14 },
  { keyword: "mixed herbs", weight: 3, categoryId: 14 },
  { keyword: "italian herbs", weight: 3, categoryId: 14 },
  { keyword: "garam masala", weight: 3, categoryId: 14 },

  // ============================================================
  // OILS & DRESSINGS
  // ============================================================

  { keyword: "cooking oil", weight: 3, categoryId: 15 },
  { keyword: "olive oil", weight: 3, categoryId: 15 },
  { keyword: "extra virgin olive oil", weight: 3, categoryId: 15 },
  { keyword: "evoo", weight: 3, categoryId: 15 },
  { keyword: "vegetable oil", weight: 3, categoryId: 15 },
  { keyword: "canola oil", weight: 3, categoryId: 15 },
  { keyword: "sunflower oil", weight: 3, categoryId: 15 },
  { keyword: "avocado oil", weight: 3, categoryId: 15 },
  { keyword: "sesame oil", weight: 3, categoryId: 15 },
  { keyword: "coconut oil", weight: 3, categoryId: 15 },
  { keyword: "peanut oil", weight: 3, categoryId: 15 },
  { keyword: "vinegar", weight: 3, categoryId: 15 },
  { keyword: "white vinegar", weight: 3, categoryId: 15 },
  { keyword: "red wine vinegar", weight: 3, categoryId: 15 },
  { keyword: "white wine vinegar", weight: 3, categoryId: 15 },
  { keyword: "balsamic vinegar", weight: 3, categoryId: 15 },
  { keyword: "apple cider vinegar", weight: 3, categoryId: 15 },
  { keyword: "salad dressing", weight: 3, categoryId: 15 },
  { keyword: "salad dressings", weight: 3, categoryId: 15 },
  { keyword: "italian dressing", weight: 3, categoryId: 15 },
  { keyword: "ranch dressing", weight: 3, categoryId: 15 },
  { keyword: "caesar dressing", weight: 3, categoryId: 15 },
  { keyword: "french dressing", weight: 3, categoryId: 15 },
  { keyword: "vinaigrette", weight: 3, categoryId: 15 },

  // ============================================================
  // WINE, BEER & SPIRITS
  // ============================================================

  { keyword: "alcohol", weight: 3, categoryId: 16 },
  { keyword: "beer", weight: 3, categoryId: 16 },
  { keyword: "beers", weight: 3, categoryId: 16 },
  { keyword: "lager", weight: 3, categoryId: 16 },
  { keyword: "ale", weight: 3, categoryId: 16 },
  { keyword: "pale ale", weight: 3, categoryId: 16 },
  { keyword: "ipa", weight: 3, categoryId: 16 },
  { keyword: "stout", weight: 3, categoryId: 16 },
  { keyword: "wine", weight: 3, categoryId: 16 },
  { keyword: "red wine", weight: 3, categoryId: 16 },
  { keyword: "white wine", weight: 3, categoryId: 16 },
  { keyword: "rose", weight: 3, categoryId: 16 },
  { keyword: "rosé", weight: 3, categoryId: 16 },
  { keyword: "champagne", weight: 3, categoryId: 16 },
  { keyword: "prosecco", weight: 3, categoryId: 16 },
  { keyword: "sparkling wine", weight: 3, categoryId: 16 },
  { keyword: "cider", weight: 3, categoryId: 16 },
  { keyword: "hard cider", weight: 3, categoryId: 16 },
  { keyword: "whiskey", weight: 3, categoryId: 16 },
  { keyword: "whisky", weight: 3, categoryId: 16 },
  { keyword: "vodka", weight: 3, categoryId: 16 },
  { keyword: "gin", weight: 3, categoryId: 16 },
  { keyword: "rum", weight: 3, categoryId: 16 },
  { keyword: "tequila", weight: 3, categoryId: 16 },
  { keyword: "brandy", weight: 3, categoryId: 16 },
  { keyword: "liqueur", weight: 3, categoryId: 16 },
  { keyword: "liqueurs", weight: 3, categoryId: 16 },
  { keyword: "spirits", weight: 3, categoryId: 16 },
  { keyword: "premix", weight: 3, categoryId: 16 },
  { keyword: "premixed drinks", weight: 3, categoryId: 16 },
  { keyword: "hard seltzer", weight: 3, categoryId: 16 },

  // ============================================================
  // SAUCES & CONDIMENTS
  // ============================================================

  { keyword: "sauce", weight: 2, categoryId: 17 },
  { keyword: "sauces", weight: 2, categoryId: 17 },
  { keyword: "ketchup", weight: 3, categoryId: 17 },
  { keyword: "tomato sauce", weight: 3, categoryId: 17 },
  { keyword: "tomato ketchup", weight: 3, categoryId: 17 },
  { keyword: "mayonnaise", weight: 3, categoryId: 17 },
  { keyword: "mayo", weight: 3, categoryId: 17 },
  { keyword: "mustard", weight: 3, categoryId: 17 },
  { keyword: "yellow mustard", weight: 3, categoryId: 17 },
  { keyword: "dijon mustard", weight: 3, categoryId: 17 },
  { keyword: "bbq sauce", weight: 3, categoryId: 17 },
  { keyword: "barbecue sauce", weight: 3, categoryId: 17 },
  { keyword: "soy sauce", weight: 3, categoryId: 17 },
  { keyword: "tamari", weight: 3, categoryId: 17 },
  { keyword: "hot sauce", weight: 3, categoryId: 17 },
  { keyword: "chilli sauce", weight: 3, categoryId: 17 },
  { keyword: "sweet chilli sauce", weight: 3, categoryId: 17 },
  { keyword: "teriyaki sauce", weight: 3, categoryId: 17 },
  { keyword: "fish sauce", weight: 3, categoryId: 17 },
  { keyword: "oyster sauce", weight: 3, categoryId: 17 },
  { keyword: "hoisin sauce", weight: 3, categoryId: 17 },
  { keyword: "pesto", weight: 3, categoryId: 17 },
  { keyword: "peanut butter", weight: 3, categoryId: 17 },
  { keyword: "almond butter", weight: 3, categoryId: 17 },
  { keyword: "jam", weight: 3, categoryId: 17 },
  { keyword: "marmalade", weight: 3, categoryId: 17 },
  { keyword: "honey", weight: 2, categoryId: 17 },
  { keyword: "marinade", weight: 3, categoryId: 17 },
  { keyword: "marinades", weight: 3, categoryId: 17 },
  { keyword: "relish", weight: 3, categoryId: 17 },
  { keyword: "chutney", weight: 3, categoryId: 17 },

  // ============================================================
  // SNACKS & SWEETS
  // ============================================================

  { keyword: "snack", weight: 2, categoryId: 18 },
  { keyword: "snacks", weight: 2, categoryId: 18 },
  { keyword: "chips", weight: 3, categoryId: 18 },
  { keyword: "crisps", weight: 3, categoryId: 18 },
  { keyword: "potato chips", weight: 3, categoryId: 18 },
  { keyword: "corn chips", weight: 3, categoryId: 18 },
  { keyword: "tortilla chips", weight: 3, categoryId: 18 },
  { keyword: "pretzels", weight: 3, categoryId: 18 },
  { keyword: "crackers", weight: 3, categoryId: 18 },
  { keyword: "biscuits", weight: 3, categoryId: 18 },
  { keyword: "cookies", weight: 3, categoryId: 18 },
  { keyword: "chocolate", weight: 2, categoryId: 18 },
  { keyword: "chocolate bar", weight: 3, categoryId: 18 },
  { keyword: "chocolate bars", weight: 3, categoryId: 18 },
  { keyword: "lollies", weight: 3, categoryId: 18 },
  { keyword: "candy", weight: 3, categoryId: 18 },
  { keyword: "gummy lollies", weight: 3, categoryId: 18 },
  { keyword: "gummy bears", weight: 3, categoryId: 18 },
  { keyword: "sweets", weight: 3, categoryId: 18 },
  { keyword: "popcorn", weight: 3, categoryId: 18 },
  { keyword: "microwave popcorn", weight: 3, categoryId: 18 },
  { keyword: "nuts", weight: 2, categoryId: 18 },
  { keyword: "mixed nuts", weight: 3, categoryId: 18 },
  { keyword: "cashews", weight: 3, categoryId: 18 },
  { keyword: "almonds", weight: 3, categoryId: 18 },
  { keyword: "trail mix", weight: 3, categoryId: 18 },
  { keyword: "muesli bars", weight: 2, categoryId: 18 },
  { keyword: "protein bars", weight: 2, categoryId: 18 },
  { keyword: "pretzel", weight: 3, categoryId: 18 },

  // ============================================================
  // DELI
  // ============================================================

  { keyword: "deli", weight: 3, categoryId: 19 },
  { keyword: "deli meat", weight: 3, categoryId: 19 },
  { keyword: "cold cuts", weight: 3, categoryId: 19 },
  { keyword: "sliced meat", weight: 3, categoryId: 19 },
  { keyword: "sliced ham", weight: 3, categoryId: 19 },
  { keyword: "deli ham", weight: 3, categoryId: 19 },
  { keyword: "salami", weight: 3, categoryId: 19 },
  { keyword: "prosciutto", weight: 3, categoryId: 19 },
  { keyword: "mortadella", weight: 3, categoryId: 19 },
  { keyword: "pastrami", weight: 3, categoryId: 19 },
  { keyword: "deli roast beef", weight: 3, categoryId: 19 },
  { keyword: "antipasto", weight: 3, categoryId: 19 },
  { keyword: "olives", weight: 3, categoryId: 19 },
  { keyword: "deli olives", weight: 3, categoryId: 19 },
  { keyword: "marinated olives", weight: 3, categoryId: 19 },
  { keyword: "hummus", weight: 3, categoryId: 19 },
  { keyword: "dip", weight: 2, categoryId: 19 },
  { keyword: "dips", weight: 2, categoryId: 19 },
  { keyword: "tzatziki", weight: 3, categoryId: 19 },
  { keyword: "guacamole", weight: 3, categoryId: 19 },
  { keyword: "tapenade", weight: 3, categoryId: 19 },
  { keyword: "specialty cheese", weight: 3, categoryId: 19 },
  { keyword: "gourmet cheese", weight: 3, categoryId: 19 },
  { keyword: "brie", weight: 3, categoryId: 19 },
  { keyword: "camembert", weight: 3, categoryId: 19 },
  { keyword: "blue cheese", weight: 3, categoryId: 19 },
  { keyword: "antipasti", weight: 3, categoryId: 19 },

  // ============================================================
  // SEAFOOD
  // ============================================================

  { keyword: "seafood", weight: 3, categoryId: 20 },
  { keyword: "fish", weight: 3, categoryId: 20 },
  { keyword: "fresh fish", weight: 3, categoryId: 20 },
  { keyword: "salmon", weight: 3, categoryId: 20 },
  { keyword: "salmon fillet", weight: 3, categoryId: 20 },
  { keyword: "salmon steak", weight: 3, categoryId: 20 },
  { keyword: "tuna steak", weight: 3, categoryId: 20 },
  { keyword: "fresh tuna", weight: 3, categoryId: 20 },
  { keyword: "cod", weight: 3, categoryId: 20 },
  { keyword: "barramundi", weight: 3, categoryId: 20 },
  { keyword: "snapper", weight: 3, categoryId: 20 },
  { keyword: "flathead", weight: 3, categoryId: 20 },
  { keyword: "sardines", weight: 3, categoryId: 20 },
  { keyword: "mackerel", weight: 3, categoryId: 20 },
  { keyword: "prawns", weight: 3, categoryId: 20 },
  { keyword: "prawn", weight: 3, categoryId: 20 },
  { keyword: "shrimp", weight: 3, categoryId: 20 },
  { keyword: "crab", weight: 3, categoryId: 20 },
  { keyword: "crab meat", weight: 3, categoryId: 20 },
  { keyword: "lobster", weight: 3, categoryId: 20 },
  { keyword: "oysters", weight: 3, categoryId: 20 },
  { keyword: "oyster", weight: 3, categoryId: 20 },
  { keyword: "mussels", weight: 3, categoryId: 20 },
  { keyword: "scallops", weight: 3, categoryId: 20 },
  { keyword: "calamari", weight: 3, categoryId: 20 },
  { keyword: "squid", weight: 3, categoryId: 20 },
  { keyword: "fish fillets", weight: 3, categoryId: 20 },
  { keyword: "fish fingers", weight: 2, categoryId: 20 },

  // ============================================================
  // STATIONERY
  // ============================================================

  { keyword: "stationery", weight: 3, categoryId: 21 },
  { keyword: "stationary", weight: 2, categoryId: 21 },
  { keyword: "office supplies", weight: 3, categoryId: 21 },
  { keyword: "school supplies", weight: 3, categoryId: 21 },
  { keyword: "pens", weight: 3, categoryId: 21 },
  { keyword: "pen", weight: 3, categoryId: 21 },
  { keyword: "ballpoint pen", weight: 3, categoryId: 21 },
  { keyword: "pencils", weight: 3, categoryId: 21 },
  { keyword: "pencil", weight: 3, categoryId: 21 },
  { keyword: "mechanical pencil", weight: 3, categoryId: 21 },
  { keyword: "notebook", weight: 3, categoryId: 21 },
  { keyword: "notebooks", weight: 3, categoryId: 21 },
  { keyword: "exercise book", weight: 3, categoryId: 21 },
  { keyword: "exercise books", weight: 3, categoryId: 21 },
  { keyword: "sticky notes", weight: 3, categoryId: 21 },
  { keyword: "post it notes", weight: 3, categoryId: 21 },
  { keyword: "markers", weight: 3, categoryId: 21 },
  { keyword: "marker", weight: 3, categoryId: 21 },
  { keyword: "highlighters", weight: 3, categoryId: 21 },
  { keyword: "highlighter", weight: 3, categoryId: 21 },
  { keyword: "envelopes", weight: 3, categoryId: 21 },
  { keyword: "envelope", weight: 3, categoryId: 21 },
  { keyword: "tape", weight: 2, categoryId: 21 },
  { keyword: "sticky tape", weight: 3, categoryId: 21 },
  { keyword: "glue", weight: 2, categoryId: 21 },
  { keyword: "glue stick", weight: 3, categoryId: 21 },
  { keyword: "rubber", weight: 2, categoryId: 21 },
  { keyword: "eraser", weight: 3, categoryId: 21 },
  { keyword: "ruler", weight: 3, categoryId: 21 },
  { keyword: "scissors", weight: 3, categoryId: 21 },
  { keyword: "folders", weight: 3, categoryId: 21 },
  { keyword: "folder", weight: 3, categoryId: 21 },
  { keyword: "filing", weight: 2, categoryId: 21 },
];
