export const categories = [
  {
    slug: "frozen_foods",
    displayName: "Frozen Foods",
  },
  {
    slug: "dairy_eggs_cheese",
    displayName: "Dairy, Eggs & Cheese",
  },
  {
    slug: "fruit_veg",
    displayName: "Fruit & Veg",
  },
  {
    slug: "household_items",
    displayName: "Household Items",
  },
  {
    slug: "meat",
    displayName: "Meat",
  },
  {
    slug: "coffee_tea",
    displayName: "Coffee & Tea",
  },
  {
    slug: "beverages",
    displayName: "Beverages",
  },
  {
    slug: "breads_cereals",
    displayName: "Bread & Cereals",
  },
  {
    slug: "pasta_rice_beans",
    displayName: "Pasta, Rice & Beans",
  },
  {
    slug: "canned_foods_soups",
    displayName: "Canned Foods & Soups",
  },
  {
    slug: "personal_care_health",
    displayName: "Personal Care & Health",
  },
  {
    slug: "pet_care",
    displayName: "Pet Care",
  },
  {
    slug: "baking_items",
    displayName: "Baking Items",
  },
  {
    slug: "spices_seasonings",
    displayName: "Spices & Seasonings",
  },
  {
    slug: "oils_dressings",
    displayName: "Oils & Dressings",
  },
  {
    slug: "wine_beer_spirits",
    displayName: "Wine, Beer & Spirits",
  },
  {
    slug: "sauces_condiments",
    displayName: "Sauces & Condiments",
  },
  {
    slug: "snacks_sweets",
    displayName: "Snacks & Sweets",
  },
  {
    slug: "deli",
    displayName: "Deli",
  },
  {
    slug: "seafood",
    displayName: "Seafood",
  },
  {
    slug: "stationery",
    displayName: "Stationery",
  },
];

export const categoryKeywords = [
  // ============================================================
  // FROZEN FOODS
  // ============================================================
  // Standalone indicators
  { keyword: "frozen", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "freezer", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "freeze", weight: 1, categorySlug: "frozen_foods" },
  // Inherent items
  { keyword: "ice cream", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "icecream", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "gelato", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "sorbet", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "popsicle", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "popsicles", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "ice pop", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "frozen yogurt", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "frozen yoghurt", weight: 3, categorySlug: "frozen_foods" },
  // Predominant
  { keyword: "hash browns", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "hashbrowns", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "tater tots", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "tv dinner", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "hot pockets", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "pizza rolls", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "fish fingers", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "fish sticks", weight: 3, categorySlug: "frozen_foods" },
  { keyword: "eggo", weight: 3, categorySlug: "frozen_foods" },
  // Compound strings
  { keyword: "frozen veggies", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen veg", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen vegetables", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen berries", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen fruit", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen meal", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen meals", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen pizza", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen dumplings", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen spring rolls", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen pie", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen pies", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen sausage rolls", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen garlic bread", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen waffles", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen pancakes", weight: 2, categorySlug: "frozen_foods" },
  // Often elsewhere
  { keyword: "chicken nuggets", weight: 1, categorySlug: "frozen_foods" },
  { keyword: "frozen nuggets", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "french fries", weight: 1, categorySlug: "frozen_foods" },
  { keyword: "frozen fries", weight: 2, categorySlug: "frozen_foods" },
  { keyword: "frozen chips", weight: 1, categorySlug: "frozen_foods" },
  { keyword: "frozen fish", weight: 1, categorySlug: "frozen_foods" },
  { keyword: "frozen shrimp", weight: 1, categorySlug: "frozen_foods" },
  { keyword: "frozen prawns", weight: 1, categorySlug: "frozen_foods" },
  { keyword: "frozen chicken", weight: 1, categorySlug: "frozen_foods" },
  // Clear exclusions
  { keyword: "fresh", weight: -3, categorySlug: "frozen_foods" },
  { keyword: "canned", weight: -3, categorySlug: "frozen_foods" },
  { keyword: "can", weight: -2, categorySlug: "frozen_foods" },
  { keyword: "tin", weight: -2, categorySlug: "frozen_foods" },
  { keyword: "tinned", weight: -3, categorySlug: "frozen_foods" },
  { keyword: "raw", weight: -1, categorySlug: "frozen_foods" },
  { keyword: "dried", weight: -3, categorySlug: "frozen_foods" },
  { keyword: "dry", weight: -1, categorySlug: "frozen_foods" },

  // ============================================================
  // DAIRY, EGGS & CHEESE
  // ============================================================
  // Inherent items
  { keyword: "dairy", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "cheese", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "yoghurt", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "yogurt", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "greek yoghurt", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "greek yogurt", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "butter", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "margarine", weight: 3, categorySlug: "dairy_eggs_cheese" },
  {
    keyword: "spreadable butter",
    weight: 3,
    categorySlug: "dairy_eggs_cheese",
  },
  // Eggs
  { keyword: "eggs", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "egg", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "free range eggs", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "egg whites", weight: 3, categorySlug: "dairy_eggs_cheese" },
  // Specific cheeses
  { keyword: "cheddar", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "tasty cheese", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "mozzarella", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "parmesan", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "parmesan cheese", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "feta", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "halloumi", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "brie", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "camembert", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "cottage cheese", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "ricotta", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "cream cheese", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "swiss cheese", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "gouda", weight: 3, categorySlug: "dairy_eggs_cheese" },
  // Milk
  { keyword: "milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "full cream milk", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "full cream", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "skim milk", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "low fat milk", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "long life milk", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "uht milk", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "condensed milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "evaporated milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  // Milk alternatives
  { keyword: "soy milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "oat milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "almond milk", weight: 2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "coconut milk", weight: 1, categorySlug: "dairy_eggs_cheese" },
  // Creams & chilled desserts
  { keyword: "cream", weight: 1, categorySlug: "dairy_eggs_cheese" },
  { keyword: "thickened cream", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "sour cream", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "whipping cream", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "double cream", weight: 3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "custard", weight: 2, categorySlug: "dairy_eggs_cheese" },
  // Exclusions
  { keyword: "frozen", weight: -2, categorySlug: "dairy_eggs_cheese" },
  { keyword: "ice cream", weight: -3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "icecream", weight: -3, categorySlug: "dairy_eggs_cheese" },
  { keyword: "chocolate", weight: -1, categorySlug: "dairy_eggs_cheese" },
  { keyword: "plant", weight: -1, categorySlug: "dairy_eggs_cheese" },

  // ============================================================
  // FRUIT & VEG
  // ============================================================
  // Inherent items
  { keyword: "fruit", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "fruits", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "vegetable", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "vegetables", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "veg", weight: 2, categorySlug: "fruit_veg" },
  { keyword: "produce", weight: 3, categorySlug: "fruit_veg" },
  // Fruits
  { keyword: "apples", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "apple", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "bananas", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "banana", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "oranges", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "orange", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "mandarins", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "mandarin", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "lemons", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "lemon", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "limes", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "lime", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "grapes", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "grape", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "strawberries", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "strawberry", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "blueberries", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "blueberry", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "raspberries", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "raspberry", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "pears", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "pear", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "peaches", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "peach", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "plums", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "plum", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "kiwi", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "kiwifruit", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "mango", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "mangoes", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "watermelon", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "pineapple", weight: 3, categorySlug: "fruit_veg" },
  // Vegetables & Roots
  { keyword: "avocado", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "avocados", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "tomatoes", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "tomato", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "potatoes", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "potato", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "sweet potato", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "carrots", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "carrot", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "onions", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "onion", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "garlic", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "ginger", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "broccoli", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "cauliflower", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "spinach", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "lettuce", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "cucumber", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "capsicum", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "bell pepper", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "zucchini", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "courgette", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "eggplant", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "aubergine", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "mushrooms", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "mushroom", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "celery", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "cabbage", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "kale", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "brussels sprouts", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "beetroot", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "spring onions", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "leek", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "pumpkin", weight: 3, categorySlug: "fruit_veg" },
  { keyword: "green beans", weight: 3, categorySlug: "fruit_veg" },
  // Ambiguous terms
  { keyword: "beans", weight: 1, categorySlug: "fruit_veg" },
  { keyword: "corn", weight: 1, categorySlug: "fruit_veg" },
  // Exclusions
  { keyword: "frozen", weight: -3, categorySlug: "fruit_veg" },
  { keyword: "canned", weight: -3, categorySlug: "fruit_veg" },
  { keyword: "dried", weight: -3, categorySlug: "fruit_veg" },
  { keyword: "tinned", weight: -3, categorySlug: "fruit_veg" },

  // ============================================================
  // HOUSEHOLD ITEMS
  // ============================================================
  // Cleaning & laundry products
  { keyword: "laundry detergent", weight: 3, categorySlug: "household_items" },
  { keyword: "laundry powder", weight: 3, categorySlug: "household_items" },
  { keyword: "washing powder", weight: 3, categorySlug: "household_items" },
  { keyword: "washing liquid", weight: 3, categorySlug: "household_items" },
  { keyword: "fabric softener", weight: 3, categorySlug: "household_items" },
  { keyword: "dishwashing liquid", weight: 3, categorySlug: "household_items" },
  { keyword: "dish soap", weight: 3, categorySlug: "household_items" },
  { keyword: "dishwasher tablets", weight: 3, categorySlug: "household_items" },
  { keyword: "dishwasher powder", weight: 3, categorySlug: "household_items" },
  { keyword: "surface cleaner", weight: 3, categorySlug: "household_items" },
  { keyword: "glass cleaner", weight: 3, categorySlug: "household_items" },
  { keyword: "window cleaner", weight: 3, categorySlug: "household_items" },
  { keyword: "floor cleaner", weight: 3, categorySlug: "household_items" },
  { keyword: "disinfectant", weight: 3, categorySlug: "household_items" },
  { keyword: "bleach", weight: 3, categorySlug: "household_items" },
  {
    keyword: "multipurpose cleaner",
    weight: 3,
    categorySlug: "household_items",
  },
  {
    keyword: "all purpose cleaner",
    weight: 3,
    categorySlug: "household_items",
  },
  { keyword: "air freshener", weight: 3, categorySlug: "household_items" },
  // Sponges & tools
  { keyword: "sponges", weight: 3, categorySlug: "household_items" },
  { keyword: "sponge", weight: 2, categorySlug: "household_items" },
  { keyword: "scrubbers", weight: 3, categorySlug: "household_items" },
  { keyword: "steel wool", weight: 3, categorySlug: "household_items" },
  { keyword: "microfiber cloth", weight: 3, categorySlug: "household_items" },
  // Paper products & disposables
  { keyword: "paper towels", weight: 3, categorySlug: "household_items" },
  { keyword: "paper towel", weight: 3, categorySlug: "household_items" },
  { keyword: "toilet paper", weight: 3, categorySlug: "household_items" },
  { keyword: "toilet rolls", weight: 3, categorySlug: "household_items" },
  { keyword: "tissues", weight: 3, categorySlug: "household_items" },
  { keyword: "facial tissues", weight: 3, categorySlug: "household_items" },
  { keyword: "napkins", weight: 2, categorySlug: "household_items" },
  // Trash & food storage
  { keyword: "bin bags", weight: 3, categorySlug: "household_items" },
  { keyword: "bin liners", weight: 3, categorySlug: "household_items" },
  { keyword: "garbage bags", weight: 3, categorySlug: "household_items" },
  { keyword: "trash bags", weight: 3, categorySlug: "household_items" },
  { keyword: "aluminium foil", weight: 3, categorySlug: "household_items" },
  { keyword: "aluminum foil", weight: 3, categorySlug: "household_items" },
  { keyword: "tin foil", weight: 3, categorySlug: "household_items" },
  { keyword: "cling wrap", weight: 3, categorySlug: "household_items" },
  { keyword: "plastic wrap", weight: 3, categorySlug: "household_items" },
  { keyword: "saran wrap", weight: 3, categorySlug: "household_items" },
  { keyword: "food storage bags", weight: 3, categorySlug: "household_items" },
  { keyword: "zip lock bags", weight: 3, categorySlug: "household_items" },
  { keyword: "ziploc", weight: 3, categorySlug: "household_items" },
  // Hardware & general household
  { keyword: "batteries", weight: 3, categorySlug: "household_items" },
  { keyword: "light bulbs", weight: 3, categorySlug: "household_items" },
  { keyword: "lightbulb", weight: 3, categorySlug: "household_items" },
  { keyword: "matches", weight: 2, categorySlug: "household_items" },
  // Ambiguous terms
  { keyword: "baking paper", weight: 1, categorySlug: "household_items" },
  { keyword: "parchment paper", weight: 1, categorySlug: "household_items" },
  { keyword: "cleaner", weight: 1, categorySlug: "household_items" },
  { keyword: "detergent", weight: 2, categorySlug: "household_items" },
  { keyword: "soap", weight: 1, categorySlug: "household_items" },
  // Exclusions
  { keyword: "food", weight: -3, categorySlug: "household_items" },
  { keyword: "body wash", weight: -3, categorySlug: "household_items" },
  { keyword: "shampoo", weight: -3, categorySlug: "household_items" },

  // ============================================================
  // MEAT
  // ============================================================
  // Inherent items
  { keyword: "meat", weight: 3, categorySlug: "meat" },
  // Chicken & poultry
  { keyword: "chicken", weight: 2, categorySlug: "meat" },
  { keyword: "chicken breast", weight: 3, categorySlug: "meat" },
  { keyword: "chicken thigh", weight: 3, categorySlug: "meat" },
  { keyword: "chicken thighs", weight: 3, categorySlug: "meat" },
  { keyword: "chicken drumsticks", weight: 3, categorySlug: "meat" },
  { keyword: "chicken wings", weight: 3, categorySlug: "meat" },
  { keyword: "whole chicken", weight: 3, categorySlug: "meat" },
  { keyword: "turkey", weight: 2, categorySlug: "meat" },
  { keyword: "duck", weight: 3, categorySlug: "meat" },
  // Beef & cuts
  { keyword: "beef", weight: 3, categorySlug: "meat" },
  { keyword: "beef mince", weight: 3, categorySlug: "meat" },
  { keyword: "minced beef", weight: 3, categorySlug: "meat" },
  { keyword: "steak", weight: 3, categorySlug: "meat" },
  { keyword: "rump steak", weight: 3, categorySlug: "meat" },
  { keyword: "scotch fillet", weight: 3, categorySlug: "meat" },
  { keyword: "sirloin", weight: 3, categorySlug: "meat" },
  { keyword: "ribeye", weight: 3, categorySlug: "meat" },
  { keyword: "t-bone", weight: 3, categorySlug: "meat" },
  { keyword: "beef roast", weight: 3, categorySlug: "meat" },
  { keyword: "beef brisket", weight: 3, categorySlug: "meat" },
  // Pork & cuts
  { keyword: "pork", weight: 3, categorySlug: "meat" },
  { keyword: "pork chops", weight: 3, categorySlug: "meat" },
  { keyword: "pork belly", weight: 3, categorySlug: "meat" },
  { keyword: "pork loin", weight: 3, categorySlug: "meat" },
  { keyword: "pork mince", weight: 3, categorySlug: "meat" },
  { keyword: "bacon", weight: 3, categorySlug: "meat" },
  // Lamb & veal
  { keyword: "lamb", weight: 3, categorySlug: "meat" },
  { keyword: "lamb chops", weight: 3, categorySlug: "meat" },
  { keyword: "lamb shanks", weight: 3, categorySlug: "meat" },
  { keyword: "lamb roast", weight: 3, categorySlug: "meat" },
  { keyword: "lamb mince", weight: 3, categorySlug: "meat" },
  { keyword: "veal", weight: 3, categorySlug: "meat" },
  // Sausages & processed fresh meat
  { keyword: "sausages", weight: 3, categorySlug: "meat" },
  { keyword: "sausage", weight: 2, categorySlug: "meat" },
  { keyword: "bratwurst", weight: 3, categorySlug: "meat" },
  { keyword: "chorizo", weight: 2, categorySlug: "meat" },
  // Ambiguous items
  { keyword: "mince", weight: 1, categorySlug: "meat" },
  { keyword: "ham", weight: 1, categorySlug: "meat" },
  { keyword: "roast beef", weight: 1, categorySlug: "meat" },
  { keyword: "salami", weight: 1, categorySlug: "meat" },
  { keyword: "prosciutto", weight: 1, categorySlug: "meat" },
  { keyword: "prosciutto", weight: 1, categorySlug: "meat" },
  // Exclusions
  { keyword: "frozen", weight: -2, categorySlug: "meat" },
  { keyword: "canned", weight: -3, categorySlug: "meat" },
  { keyword: "tinned", weight: -3, categorySlug: "meat" },
  { keyword: "dog food", weight: -3, categorySlug: "meat" },
  { keyword: "cat food", weight: -3, categorySlug: "meat" },
  { keyword: "pet food", weight: -3, categorySlug: "meat" },
  { keyword: "plant based", weight: -3, categorySlug: "meat" },
  { keyword: "vegan", weight: -3, categorySlug: "meat" },
  { keyword: "vegetarian", weight: -3, categorySlug: "meat" },

  // ============================================================
  // COFFEE & TEA
  // ============================================================
  // Inherent items
  { keyword: "coffee", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "coffee beans", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "ground coffee", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "instant coffee", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "coffee pods", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "coffee capsules", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "nespresso", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "decaf coffee", weight: 3, categorySlug: "coffee_tea" },
  // Tea & varieties
  { keyword: "tea", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "tea bags", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "teabags", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "loose leaf tea", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "black tea", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "green tea", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "herbal tea", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "peppermint tea", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "camomile tea", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "chamomile tea", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "chai", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "chai tea", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "chai latte", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "earl grey", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "english breakfast tea", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "matcha", weight: 3, categorySlug: "coffee_tea" },
  // Hot chocolate & malt drinks
  { keyword: "hot chocolate", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "hot chocolate powder", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "drinking chocolate", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "milo", weight: 3, categorySlug: "coffee_tea" },
  { keyword: "nesquik", weight: 2, categorySlug: "coffee_tea" },
  // Ambiguous items
  { keyword: "espresso", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "cocoa drink", weight: 2, categorySlug: "coffee_tea" },
  { keyword: "cocoa", weight: 1, categorySlug: "coffee_tea" },
  // Exclusions
  { keyword: "iced tea", weight: -2, categorySlug: "coffee_tea" },
  { keyword: "iced coffee", weight: -2, categorySlug: "coffee_tea" },
  { keyword: "kombucha", weight: -3, categorySlug: "coffee_tea" },
  { keyword: "cocoa powder", weight: -2, categorySlug: "coffee_tea" },
  { keyword: "baking cocoa", weight: -3, categorySlug: "coffee_tea" },

  // ============================================================
  // BEVERAGES
  // ============================================================
  // Water & hydration
  { keyword: "bottled water", weight: 3, categorySlug: "beverages" },
  { keyword: "sparkling water", weight: 3, categorySlug: "beverages" },
  { keyword: "mineral water", weight: 3, categorySlug: "beverages" },
  { keyword: "soda water", weight: 3, categorySlug: "beverages" },
  { keyword: "tonic water", weight: 3, categorySlug: "beverages" },
  // Soft drinks & sodas
  { keyword: "soda", weight: 3, categorySlug: "beverages" },
  { keyword: "soft drink", weight: 3, categorySlug: "beverages" },
  { keyword: "soft drinks", weight: 3, categorySlug: "beverages" },
  { keyword: "coke", weight: 3, categorySlug: "beverages" },
  { keyword: "cola", weight: 3, categorySlug: "beverages" },
  { keyword: "lemonade", weight: 3, categorySlug: "beverages" },
  { keyword: "ginger ale", weight: 3, categorySlug: "beverages" },
  { keyword: "ginger beer", weight: 3, categorySlug: "beverages" },
  // Juices & fruit drinks
  { keyword: "juice", weight: 2, categorySlug: "beverages" },
  { keyword: "fruit juice", weight: 3, categorySlug: "beverages" },
  { keyword: "orange juice", weight: 3, categorySlug: "beverages" },
  { keyword: "apple juice", weight: 3, categorySlug: "beverages" },
  { keyword: "cranberry juice", weight: 3, categorySlug: "beverages" },
  { keyword: "pineapple juice", weight: 3, categorySlug: "beverages" },
  // Ready-to-drink teas, coffees & fermented Beverages
  { keyword: "iced tea", weight: 3, categorySlug: "beverages" },
  { keyword: "iced coffee", weight: 3, categorySlug: "beverages" },
  { keyword: "kombucha", weight: 3, categorySlug: "beverages" },
  // Energy, sports & concentrates
  { keyword: "sports drink", weight: 3, categorySlug: "beverages" },
  { keyword: "energy drink", weight: 3, categorySlug: "beverages" },
  { keyword: "energy drinks", weight: 3, categorySlug: "beverages" },
  { keyword: "electrolyte drink", weight: 3, categorySlug: "beverages" },
  { keyword: "cordial", weight: 3, categorySlug: "beverages" },
  // Ambiguous terms
  { keyword: "water", weight: 1, categorySlug: "beverages" },
  { keyword: "squash", weight: 1, categorySlug: "beverages" },
  // Exclusions
  { keyword: "beer", weight: -2, categorySlug: "beverages" },
  { keyword: "wine", weight: -3, categorySlug: "beverages" },
  { keyword: "spirits", weight: -3, categorySlug: "beverages" },
  { keyword: "powder", weight: -2, categorySlug: "beverages" },
  { keyword: "tea bags", weight: -3, categorySlug: "beverages" },
  { keyword: "ground coffee", weight: -3, categorySlug: "beverages" },

  // ============================================================
  // BREAD & CEREALS
  // ============================================================
  // Breads & rolls
  { keyword: "bread", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "white bread", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "wholemeal bread", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "wholegrain bread", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "sourdough", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "rye bread", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "multigrain bread", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "toast bread", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "bagels", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "bagel", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "english muffins", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "crumpets", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "pita bread", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "naan bread", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "brioche", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "croissant", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "croissants", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "bread rolls", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "hamburger buns", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "burger buns", weight: 3, categorySlug: "breads_cereals" },
  // Wraps & flatbreads
  { keyword: "tortilla wraps", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "tortillas", weight: 2, categorySlug: "breads_cereals" },
  // Breakfast cereals & oats
  { keyword: "cereal", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "breakfast cereal", weight: 2, categorySlug: "breads_cereals" },
  { keyword: "corn flakes", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "rice bubbles", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "weetbix", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "weet-bix", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "muesli", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "granola", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "oats", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "rolled oats", weight: 3, categorySlug: "breads_cereals" },
  { keyword: "porridge", weight: 3, categorySlug: "breads_cereals" },
  // Ambiguous terms
  { keyword: "toast", weight: 1, categorySlug: "breads_cereals" },
  { keyword: "wraps", weight: 1, categorySlug: "breads_cereals" },
  { keyword: "breakfast bars", weight: 1, categorySlug: "breads_cereals" },
  { keyword: "muesli bars", weight: 1, categorySlug: "breads_cereals" },
  // Exclusions
  { keyword: "frozen", weight: -2, categorySlug: "breads_cereals" },
  {
    keyword: "frozen garlic bread",
    weight: -3,
    categorySlug: "breads_cereals",
  },
  { keyword: "crumbs", weight: -2, categorySlug: "breads_cereals" },
  { keyword: "breadcrumbs", weight: -2, categorySlug: "breads_cereals" },

  // ============================================================
  // PASTA, RICE & BEANS
  // ============================================================
  // Pasta & noodles
  { keyword: "pasta", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "spaghetti", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "penne", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "fusilli", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "fettuccine", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "linguine", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "macaroni", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "lasagne sheets", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "lasagna sheets", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "orzo", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "rigatoni", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "noodles", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "ramen noodles", weight: 2, categorySlug: "pasta_rice_beans" },
  // Grains & rice
  { keyword: "white rice", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "brown rice", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "basmati rice", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "jasmine rice", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "arborio rice", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "wild rice", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "quinoa", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "couscous", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "polenta", weight: 3, categorySlug: "pasta_rice_beans" },
  // Pulses, lentils & dried legumes
  { keyword: "lentils", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "red lentils", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "green lentils", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "brown lentils", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "dried beans", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "dried chickpeas", weight: 3, categorySlug: "pasta_rice_beans" },
  { keyword: "split peas", weight: 3, categorySlug: "pasta_rice_beans" },
  // Ambiguous pulses & grains
  { keyword: "rice", weight: 2, categorySlug: "pasta_rice_beans" },
  { keyword: "kidney beans", weight: 1, categorySlug: "pasta_rice_beans" },
  { keyword: "black beans", weight: 1, categorySlug: "pasta_rice_beans" },
  { keyword: "chickpeas", weight: 1, categorySlug: "pasta_rice_beans" },
  { keyword: "garbanzo beans", weight: 1, categorySlug: "pasta_rice_beans" },
  { keyword: "cannellini beans", weight: 1, categorySlug: "pasta_rice_beans" },
  // Exclusions
  { keyword: "canned", weight: -3, categorySlug: "pasta_rice_beans" },
  { keyword: "can", weight: -2, categorySlug: "pasta_rice_beans" },
  { keyword: "tin", weight: -2, categorySlug: "pasta_rice_beans" },
  { keyword: "tinned", weight: -3, categorySlug: "pasta_rice_beans" },
  { keyword: "baked beans", weight: -3, categorySlug: "pasta_rice_beans" },
  { keyword: "frozen", weight: -3, categorySlug: "pasta_rice_beans" },
  { keyword: "fresh pasta", weight: -1, categorySlug: "pasta_rice_beans" },

  // ============================================================
  // CANNED FOODS & SOUPS
  // ============================================================
  // Inherent items
  { keyword: "canned", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "tinned", weight: 3, categorySlug: "canned_foods_soups" },
  // Soups, broths & stocks
  { keyword: "soup", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "soups", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "canned soup", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "tinned soup", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "broth", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "bone broth", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "stock", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "chicken stock", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "beef stock", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "vegetable stock", weight: 3, categorySlug: "canned_foods_soups" },
  // Canned tomato products
  { keyword: "canned tomatoes", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "tinned tomatoes", weight: 3, categorySlug: "canned_foods_soups" },
  {
    keyword: "crushed tomatoes",
    weight: 3,
    categorySlug: "canned_foods_soups",
  },
  { keyword: "diced tomatoes", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "passata", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "tomato paste", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "tomato puree", weight: 2, categorySlug: "canned_foods_soups" },
  // Canned legumes & baked beans
  { keyword: "baked beans", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "canned beans", weight: 3, categorySlug: "canned_foods_soups" },
  {
    keyword: "canned chickpeas",
    weight: 3,
    categorySlug: "canned_foods_soups",
  },
  { keyword: "canned lentils", weight: 3, categorySlug: "canned_foods_soups" },
  {
    keyword: "canned kidney beans",
    weight: 3,
    categorySlug: "canned_foods_soups",
  },
  {
    keyword: "canned black beans",
    weight: 3,
    categorySlug: "canned_foods_soups",
  },
  // Canned seafood & meats
  { keyword: "canned tuna", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "tinned tuna", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "canned salmon", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "tinned salmon", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "sardines", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "anchovies", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "spam", weight: 3, categorySlug: "canned_foods_soups" },
  // Canned vegetables & fruits
  { keyword: "canned corn", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "canned fruit", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "canned peaches", weight: 3, categorySlug: "canned_foods_soups" },
  {
    keyword: "canned pineapple",
    weight: 3,
    categorySlug: "canned_foods_soups",
  },
  { keyword: "canned beetroot", weight: 3, categorySlug: "canned_foods_soups" },
  { keyword: "coconut milk", weight: 2, categorySlug: "canned_foods_soups" },
  { keyword: "coconut cream", weight: 2, categorySlug: "canned_foods_soups" },
  // Ambiguous term
  { keyword: "tin", weight: 1, categorySlug: "canned_foods_soups" },
  // Exclusions
  { keyword: "fresh", weight: -3, categorySlug: "canned_foods_soups" },
  { keyword: "frozen", weight: -3, categorySlug: "canned_foods_soups" },
  { keyword: "dried", weight: -3, categorySlug: "canned_foods_soups" },
  { keyword: "pet food", weight: -3, categorySlug: "canned_foods_soups" },
  { keyword: "cat food", weight: -3, categorySlug: "canned_foods_soups" },
  { keyword: "dog food", weight: -3, categorySlug: "canned_foods_soups" },

  // ============================================================
  // PERSONAL CARE & HEALTH
  // ============================================================
  // Hair care
  { keyword: "shampoo", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "conditioner", weight: 2, categorySlug: "personal_care_health" },
  {
    keyword: "hair conditioner",
    weight: 3,
    categorySlug: "personal_care_health",
  },
  { keyword: "dry shampoo", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "hair gel", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "hair spray", weight: 3, categorySlug: "personal_care_health" },
  // Body wash & cleansers
  { keyword: "body wash", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "shower gel", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "soap", weight: 2, categorySlug: "personal_care_health" },
  { keyword: "hand soap", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "hand wash", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "bar soap", weight: 3, categorySlug: "personal_care_health" },
  // Oral hygiene
  { keyword: "toothpaste", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "toothbrush", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "mouthwash", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "floss", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "dental floss", weight: 3, categorySlug: "personal_care_health" },
  // Deodorants & grooming
  { keyword: "deodorant", weight: 3, categorySlug: "personal_care_health" },
  {
    keyword: "antiperspirant",
    weight: 3,
    categorySlug: "personal_care_health",
  },
  { keyword: "razors", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "shaving cream", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "shaving gel", weight: 3, categorySlug: "personal_care_health" },
  // Skincare & sun protection
  { keyword: "sunscreen", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "sun cream", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "moisturiser", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "moisturizer", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "lip balm", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "face wash", weight: 3, categorySlug: "personal_care_health" },
  {
    keyword: "facial cleanser",
    weight: 3,
    categorySlug: "personal_care_health",
  },
  // Pharmacy, vitamins & first aid
  { keyword: "vitamins", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "vitamin", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "supplements", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "pain relief", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "pain reliever", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "paracetamol", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "ibuprofen", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "aspirin", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "bandages", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "band aids", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "band-aids", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "first aid", weight: 3, categorySlug: "personal_care_health" },
  {
    keyword: "antiseptic cream",
    weight: 3,
    categorySlug: "personal_care_health",
  },
  // Toiletries & paper accessories
  { keyword: "cotton buds", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "cotton pads", weight: 3, categorySlug: "personal_care_health" },
  { keyword: "tissues", weight: 1, categorySlug: "personal_care_health" },
  // Exclusions
  { keyword: "food", weight: -3, categorySlug: "personal_care_health" },
  { keyword: "dish soap", weight: -3, categorySlug: "personal_care_health" },
  {
    keyword: "laundry detergent",
    weight: -3,
    categorySlug: "personal_care_health",
  },

  // ============================================================
  // PET CARE
  // ============================================================
  // Pet food & treats
  { keyword: "pet food", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog food", weight: 3, categorySlug: "pet_care" },
  { keyword: "cat food", weight: 3, categorySlug: "pet_care" },
  { keyword: "puppy food", weight: 3, categorySlug: "pet_care" },
  { keyword: "kitten food", weight: 3, categorySlug: "pet_care" },
  { keyword: "bird food", weight: 3, categorySlug: "pet_care" },
  { keyword: "rabbit food", weight: 3, categorySlug: "pet_care" },
  { keyword: "guinea pig food", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog treats", weight: 3, categorySlug: "pet_care" },
  { keyword: "cat treats", weight: 3, categorySlug: "pet_care" },
  { keyword: "pet treats", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog biscuits", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog chews", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog chew", weight: 3, categorySlug: "pet_care" },
  { keyword: "bird seed", weight: 3, categorySlug: "pet_care" },
  { keyword: "birdseed", weight: 3, categorySlug: "pet_care" },
  { keyword: "fish food", weight: 3, categorySlug: "pet_care" },
  { keyword: "fish flakes", weight: 3, categorySlug: "pet_care" },
  // Litter, grooming & health
  { keyword: "cat litter", weight: 3, categorySlug: "pet_care" },
  { keyword: "kitty litter", weight: 3, categorySlug: "pet_care" },
  { keyword: "pet shampoo", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog shampoo", weight: 3, categorySlug: "pet_care" },
  { keyword: "cat shampoo", weight: 3, categorySlug: "pet_care" },
  { keyword: "flea treatment", weight: 3, categorySlug: "pet_care" },
  { keyword: "flea treatments", weight: 3, categorySlug: "pet_care" },
  { keyword: "worming tablets", weight: 3, categorySlug: "pet_care" },
  { keyword: "dewormer", weight: 3, categorySlug: "pet_care" },
  // Toys, accessories & supplies
  { keyword: "pet toys", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog toys", weight: 3, categorySlug: "pet_care" },
  { keyword: "cat toys", weight: 3, categorySlug: "pet_care" },
  { keyword: "pet bedding", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog lead", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog leash", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog collar", weight: 3, categorySlug: "pet_care" },
  { keyword: "cat collar", weight: 3, categorySlug: "pet_care" },
  { keyword: "poop bags", weight: 3, categorySlug: "pet_care" },
  { keyword: "dog waste bags", weight: 3, categorySlug: "pet_care" },
  // Ambiguous terms
  { keyword: "kibble", weight: 2, categorySlug: "pet_care" },
  { keyword: "wet food", weight: 1, categorySlug: "pet_care" },
  { keyword: "dry food", weight: 1, categorySlug: "pet_care" },
  // Exclusions
  { keyword: "human food", weight: -3, categorySlug: "pet_care" },

  // ============================================================
  // BAKING ITEMS
  // ============================================================
  // Flours & starches
  { keyword: "baking", weight: 3, categorySlug: "baking_items" },
  { keyword: "plain flour", weight: 3, categorySlug: "baking_items" },
  { keyword: "self raising flour", weight: 3, categorySlug: "baking_items" },
  { keyword: "self-raising flour", weight: 3, categorySlug: "baking_items" },
  { keyword: "flour", weight: 2, categorySlug: "baking_items" },
  { keyword: "bread flour", weight: 3, categorySlug: "baking_items" },
  { keyword: "baking flour", weight: 3, categorySlug: "baking_items" },
  { keyword: "cornflour", weight: 3, categorySlug: "baking_items" },
  { keyword: "cornstarch", weight: 3, categorySlug: "baking_items" },
  // Sugars & sweeteners
  { keyword: "caster sugar", weight: 3, categorySlug: "baking_items" },
  { keyword: "icing sugar", weight: 3, categorySlug: "baking_items" },
  { keyword: "powdered sugar", weight: 3, categorySlug: "baking_items" },
  { keyword: "brown sugar", weight: 3, categorySlug: "baking_items" },
  { keyword: "raw sugar", weight: 2, categorySlug: "baking_items" },
  { keyword: "white sugar", weight: 2, categorySlug: "baking_items" },
  // Leavening agents & additives
  { keyword: "baking powder", weight: 3, categorySlug: "baking_items" },
  { keyword: "baking soda", weight: 3, categorySlug: "baking_items" },
  { keyword: "bicarbonate soda", weight: 3, categorySlug: "baking_items" },
  { keyword: "bicarbonate of soda", weight: 3, categorySlug: "baking_items" },
  { keyword: "bicarb soda", weight: 3, categorySlug: "baking_items" },
  { keyword: "yeast", weight: 3, categorySlug: "baking_items" },
  { keyword: "gelatine", weight: 3, categorySlug: "baking_items" },
  { keyword: "gelatin", weight: 3, categorySlug: "baking_items" },
  // Flavorings, chocolate & decorating
  { keyword: "vanilla extract", weight: 3, categorySlug: "baking_items" },
  { keyword: "vanilla essence", weight: 3, categorySlug: "baking_items" },
  { keyword: "vanilla bean paste", weight: 3, categorySlug: "baking_items" },
  { keyword: "cocoa powder", weight: 3, categorySlug: "baking_items" },
  { keyword: "cacao powder", weight: 3, categorySlug: "baking_items" },
  { keyword: "chocolate chips", weight: 3, categorySlug: "baking_items" },
  { keyword: "choc chips", weight: 3, categorySlug: "baking_items" },
  { keyword: "baking chocolate", weight: 3, categorySlug: "baking_items" },
  { keyword: "cooking chocolate", weight: 3, categorySlug: "baking_items" },
  { keyword: "sprinkles", weight: 3, categorySlug: "baking_items" },
  { keyword: "food colouring", weight: 3, categorySlug: "baking_items" },
  { keyword: "food coloring", weight: 3, categorySlug: "baking_items" },
  // Pre-packaged mixes & accessories
  { keyword: "cake mix", weight: 3, categorySlug: "baking_items" },
  { keyword: "cake mixes", weight: 3, categorySlug: "baking_items" },
  { keyword: "brownie mix", weight: 3, categorySlug: "baking_items" },
  { keyword: "muffin mix", weight: 3, categorySlug: "baking_items" },
  { keyword: "pancake mix", weight: 3, categorySlug: "baking_items" },
  { keyword: "dessert mix", weight: 2, categorySlug: "baking_items" },
  { keyword: "baking paper", weight: 2, categorySlug: "baking_items" },
  { keyword: "parchment paper", weight: 2, categorySlug: "baking_items" },
  { keyword: "patty pans", weight: 3, categorySlug: "baking_items" },
  { keyword: "cupcake liners", weight: 3, categorySlug: "baking_items" },
  // Ambiguous terms
  { keyword: "sugar", weight: 1, categorySlug: "baking_items" },
  // Exclusions
  { keyword: "cocoa drink", weight: -2, categorySlug: "baking_items" },
  { keyword: "hot chocolate", weight: -3, categorySlug: "baking_items" },
  { keyword: "bread", weight: -2, categorySlug: "baking_items" },

  // ============================================================
  // SPICES & SEASONINGS
  // ============================================================
  // General categories & blends
  { keyword: "spice", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "spices", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "seasoning", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "seasonings", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "mixed herbs", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "italian herbs", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "garam masala", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "curry powder", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "taco seasoning", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "cajun seasoning", weight: 3, categorySlug: "spices_seasonings" },
  // Salt & pepper
  { keyword: "salt", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "sea salt", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "rock salt", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "table salt", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "black pepper", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "white pepper", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "peppercorns", weight: 3, categorySlug: "spices_seasonings" },
  // Ground spices & powders
  { keyword: "paprika", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "smoked paprika", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "cumin", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "ground cumin", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "cinnamon", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "ground cinnamon", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "turmeric", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "garlic powder", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "onion powder", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "nutmeg", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "chilli powder", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "chili powder", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "cardamom", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "ground ginger", weight: 3, categorySlug: "spices_seasonings" },
  // Dried herbs & seeds
  { keyword: "oregano", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "thyme", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "rosemary", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "dried basil", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "chilli flakes", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "chili flakes", weight: 3, categorySlug: "spices_seasonings" },
  { keyword: "bay leaves", weight: 3, categorySlug: "spices_seasonings" },
  // Ambiguous terms
  { keyword: "pepper", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "basil", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "chilli", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "chili", weight: 2, categorySlug: "spices_seasonings" },
  { keyword: "cloves", weight: 2, categorySlug: "spices_seasonings" },
  // Exclusions
  { keyword: "fresh basil", weight: -3, categorySlug: "spices_seasonings" },
  { keyword: "fresh rosemary", weight: -3, categorySlug: "spices_seasonings" },
  { keyword: "fresh thyme", weight: -3, categorySlug: "spices_seasonings" },
  { keyword: "bell pepper", weight: -3, categorySlug: "spices_seasonings" },
  { keyword: "capsicum", weight: -3, categorySlug: "spices_seasonings" },
  { keyword: "fresh chilli", weight: -3, categorySlug: "spices_seasonings" },
  { keyword: "fresh chili", weight: -3, categorySlug: "spices_seasonings" },

  // ============================================================
  // OILS & DRESSINGS
  // ============================================================
  // Cooking oils
  { keyword: "cooking oil", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "olive oil", weight: 3, categorySlug: "oils_dressings" },
  {
    keyword: "extra virgin olive oil",
    weight: 3,
    categorySlug: "oils_dressings",
  },
  { keyword: "evoo", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "vegetable oil", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "canola oil", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "sunflower oil", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "avocado oil", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "sesame oil", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "coconut oil", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "peanut oil", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "grapeseed oil", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "rice bran oil", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "cooking spray", weight: 3, categorySlug: "oils_dressings" },
  // Vinegars
  { keyword: "vinegar", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "white vinegar", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "red wine vinegar", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "white wine vinegar", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "balsamic vinegar", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "apple cider vinegar", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "balsamic glaze", weight: 3, categorySlug: "oils_dressings" },
  // Salad dressings & vinaigrettes
  { keyword: "salad dressing", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "salad dressings", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "italian dressing", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "ranch dressing", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "caesar dressing", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "french dressing", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "vinaigrette", weight: 3, categorySlug: "oils_dressings" },
  { keyword: "greek dressing", weight: 3, categorySlug: "oils_dressings" },
  {
    keyword: "thousand island dressing",
    weight: 3,
    categorySlug: "oils_dressings",
  },
  // Ambiguous terms
  { keyword: "oil", weight: 1, categorySlug: "oils_dressings" },
  // Exclusions
  { keyword: "essential oil", weight: -3, categorySlug: "oils_dressings" },
  { keyword: "body oil", weight: -3, categorySlug: "oils_dressings" },
  { keyword: "baby oil", weight: -3, categorySlug: "oils_dressings" },
  { keyword: "hair oil", weight: -3, categorySlug: "oils_dressings" },
  { keyword: "engine oil", weight: -3, categorySlug: "oils_dressings" },
  { keyword: "motor oil", weight: -3, categorySlug: "oils_dressings" },

  // ============================================================
  // WINE, BEER & SPIRITS
  // ============================================================
  // Beer & cider
  { keyword: "beer", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "beers", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "lager", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "ale", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "pale ale", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "ipa", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "stout", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "cider", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "hard cider", weight: 3, categorySlug: "wine_beer_spirits" },
  // Wine & sparkling
  { keyword: "wine", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "red wine", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "white wine", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "rose", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "rosé", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "champagne", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "prosecco", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "sparkling wine", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "shiraz", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "pinot noir", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "sauvignon blanc", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "chardonnay", weight: 3, categorySlug: "wine_beer_spirits" },
  // Spirits & liquors
  { keyword: "whiskey", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "whisky", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "vodka", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "gin", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "rum", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "tequila", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "brandy", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "bourbon", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "liqueur", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "liqueurs", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "spirits", weight: 3, categorySlug: "wine_beer_spirits" },
  // Premixed & RTDs
  { keyword: "premix", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "premixed drinks", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "hard seltzer", weight: 3, categorySlug: "wine_beer_spirits" },
  { keyword: "rtd", weight: 3, categorySlug: "wine_beer_spirits" },
  // Broad terms
  { keyword: "alcohol", weight: 3, categorySlug: "wine_beer_spirits" },
  // Exclusions
  { keyword: "ginger beer", weight: -2, categorySlug: "wine_beer_spirits" },
  {
    keyword: "non alcoholic beer",
    weight: -3,
    categorySlug: "wine_beer_spirits",
  },
  {
    keyword: "non-alcoholic beer",
    weight: -3,
    categorySlug: "wine_beer_spirits",
  },
  { keyword: "zero alcohol", weight: -3, categorySlug: "wine_beer_spirits" },
  { keyword: "rubbing alcohol", weight: -3, categorySlug: "wine_beer_spirits" },
  { keyword: "cooking wine", weight: -2, categorySlug: "wine_beer_spirits" },
  {
    keyword: "red wine vinegar",
    weight: -3,
    categorySlug: "wine_beer_spirits",
  },
  {
    keyword: "white wine vinegar",
    weight: -3,
    categorySlug: "wine_beer_spirits",
  },

  // ============================================================
  // SAUCES & CONDIMENTS
  // ============================================================
  // Condiments, spreads & jams
  { keyword: "ketchup", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "tomato sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "tomato ketchup", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "mayonnaise", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "mayo", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "mustard", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "yellow mustard", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "dijon mustard", weight: 3, categorySlug: "sauces_condiments" },
  {
    keyword: "wholegrain mustard",
    weight: 3,
    categorySlug: "sauces_condiments",
  },
  { keyword: "peanut butter", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "almond butter", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "nutella", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "vegemite", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "marmite", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "jam", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "marmalade", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "relish", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "chutney", weight: 3, categorySlug: "sauces_condiments" },
  // Cooking sauces, asian sauces & marinades
  { keyword: "bbq sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "barbecue sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "soy sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "tamari", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "hot sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "chilli sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "chili sauce", weight: 3, categorySlug: "sauces_condiments" },
  {
    keyword: "sweet chilli sauce",
    weight: 3,
    categorySlug: "sauces_condiments",
  },
  { keyword: "sriracha", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "teriyaki sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "fish sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "oyster sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "hoisin sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "pesto", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "pasta sauce", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "marinade", weight: 3, categorySlug: "sauces_condiments" },
  { keyword: "marinades", weight: 3, categorySlug: "sauces_condiments" },
  // Ambiguous terms
  { keyword: "sauce", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "sauces", weight: 2, categorySlug: "sauces_condiments" },
  { keyword: "honey", weight: 2, categorySlug: "sauces_condiments" },
  // Exclusions
  { keyword: "applesauce", weight: -1, categorySlug: "sauces_condiments" },
  { keyword: "canned tomatoes", weight: -3, categorySlug: "sauces_condiments" },
  { keyword: "gravy powder", weight: -2, categorySlug: "sauces_condiments" },

  // ============================================================
  // SNACKS & SWEETS
  // ============================================================
  // Savory snacks & chips
  { keyword: "chips", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "crisps", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "potato chips", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "corn chips", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "tortilla chips", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "pretzels", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "pretzel", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "crackers", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "popcorn", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "microwave popcorn", weight: 3, categorySlug: "snacks_sweets" },
  // Biscuits, cookies & confectionery
  { keyword: "biscuits", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "cookies", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "chocolate bar", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "chocolate bars", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "lollies", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "candy", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "gummy lollies", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "gummy bears", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "sweets", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "chewing gum", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "bubblegum", weight: 3, categorySlug: "snacks_sweets" },
  // Nuts, seeds & snack mixes
  { keyword: "mixed nuts", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "cashews", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "almonds", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "peanuts", weight: 3, categorySlug: "snacks_sweets" },
  { keyword: "trail mix", weight: 3, categorySlug: "snacks_sweets" },
  // Bars & ambiguous terms
  { keyword: "snack", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "snacks", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "chocolate", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "nuts", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "muesli bars", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "protein bars", weight: 2, categorySlug: "snacks_sweets" },
  { keyword: "snack bars", weight: 2, categorySlug: "snacks_sweets" },
  // Exclusions
  { keyword: "baking chocolate", weight: -3, categorySlug: "snacks_sweets" },
  { keyword: "cooking chocolate", weight: -3, categorySlug: "snacks_sweets" },
  { keyword: "chocolate chips", weight: -3, categorySlug: "snacks_sweets" },
  { keyword: "hot chocolate", weight: -3, categorySlug: "snacks_sweets" },
  { keyword: "frozen chips", weight: -3, categorySlug: "snacks_sweets" },
  { keyword: "hot chips", weight: -3, categorySlug: "snacks_sweets" },

  // ============================================================
  // DELI
  // ============================================================
  // Deli meats & charcuterie
  { keyword: "deli", weight: 3, categorySlug: "deli" },
  { keyword: "deli meat", weight: 3, categorySlug: "deli" },
  { keyword: "cold cuts", weight: 3, categorySlug: "deli" },
  { keyword: "sliced meat", weight: 3, categorySlug: "deli" },
  { keyword: "sliced ham", weight: 3, categorySlug: "deli" },
  { keyword: "deli ham", weight: 3, categorySlug: "deli" },
  { keyword: "salami", weight: 3, categorySlug: "deli" },
  { keyword: "prosciutto", weight: 3, categorySlug: "deli" },
  { keyword: "mortadella", weight: 3, categorySlug: "deli" },
  { keyword: "pastrami", weight: 3, categorySlug: "deli" },
  { keyword: "deli roast beef", weight: 3, categorySlug: "deli" },
  { keyword: "strasburg", weight: 3, categorySlug: "deli" },
  { keyword: "cabana", weight: 3, categorySlug: "deli" },
  // Olives, antipasto & dips
  { keyword: "antipasto", weight: 3, categorySlug: "deli" },
  { keyword: "antipasti", weight: 3, categorySlug: "deli" },
  { keyword: "olives", weight: 3, categorySlug: "deli" },
  { keyword: "deli olives", weight: 3, categorySlug: "deli" },
  { keyword: "marinated olives", weight: 3, categorySlug: "deli" },
  { keyword: "hummus", weight: 3, categorySlug: "deli" },
  { keyword: "tzatziki", weight: 3, categorySlug: "deli" },
  { keyword: "guacamole", weight: 3, categorySlug: "deli" },
  { keyword: "tapenade", weight: 3, categorySlug: "deli" },
  // Specialty cheeses
  { keyword: "specialty cheese", weight: 3, categorySlug: "deli" },
  { keyword: "gourmet cheese", weight: 3, categorySlug: "deli" },
  { keyword: "brie", weight: 3, categorySlug: "deli" },
  { keyword: "camembert", weight: 3, categorySlug: "deli" },
  { keyword: "blue cheese", weight: 3, categorySlug: "deli" },
  { keyword: "feta cheese", weight: 3, categorySlug: "deli" },
  { keyword: "halloumi", weight: 3, categorySlug: "deli" },
  // Ambiguous terms
  { keyword: "dip", weight: 2, categorySlug: "deli" },
  { keyword: "dips", weight: 2, categorySlug: "deli" },
  // Exclusions
  { keyword: "canned olives", weight: -2, categorySlug: "deli" },
  { keyword: "tinned olives", weight: -2, categorySlug: "deli" },
  { keyword: "fresh meat", weight: -2, categorySlug: "deli" },
  { keyword: "raw meat", weight: -3, categorySlug: "deli" },

  // ============================================================
  // SEAFOOD
  // ============================================================
  // General category identifiers
  { keyword: "seafood", weight: 3, categorySlug: "seafood" },
  { keyword: "fresh fish", weight: 3, categorySlug: "seafood" },
  { keyword: "fish fillets", weight: 3, categorySlug: "seafood" },
  // Fish varieties & cuts
  { keyword: "salmon", weight: 3, categorySlug: "seafood" },
  { keyword: "salmon fillet", weight: 3, categorySlug: "seafood" },
  { keyword: "salmon steak", weight: 3, categorySlug: "seafood" },
  { keyword: "fresh tuna", weight: 3, categorySlug: "seafood" },
  { keyword: "tuna steak", weight: 3, categorySlug: "seafood" },
  { keyword: "cod", weight: 3, categorySlug: "seafood" },
  { keyword: "barramundi", weight: 3, categorySlug: "seafood" },
  { keyword: "snapper", weight: 3, categorySlug: "seafood" },
  { keyword: "flathead", weight: 3, categorySlug: "seafood" },
  { keyword: "mackerel", weight: 3, categorySlug: "seafood" },
  { keyword: "trout", weight: 3, categorySlug: "seafood" },
  { keyword: "hoki", weight: 3, categorySlug: "seafood" },
  { keyword: "halibut", weight: 3, categorySlug: "seafood" },
  // Shellfish & crustaceans
  { keyword: "prawns", weight: 3, categorySlug: "seafood" },
  { keyword: "prawn", weight: 3, categorySlug: "seafood" },
  { keyword: "shrimp", weight: 3, categorySlug: "seafood" },
  { keyword: "crab", weight: 3, categorySlug: "seafood" },
  { keyword: "crab meat", weight: 3, categorySlug: "seafood" },
  { keyword: "lobster", weight: 3, categorySlug: "seafood" },
  { keyword: "oysters", weight: 3, categorySlug: "seafood" },
  { keyword: "oyster", weight: 3, categorySlug: "seafood" },
  { keyword: "mussels", weight: 3, categorySlug: "seafood" },
  { keyword: "scallops", weight: 3, categorySlug: "seafood" },
  { keyword: "calamari", weight: 3, categorySlug: "seafood" },
  { keyword: "squid", weight: 3, categorySlug: "seafood" },
  { keyword: "octopus", weight: 3, categorySlug: "seafood" },
  // Ambiguous terms
  { keyword: "fish", weight: 2, categorySlug: "seafood" },
  { keyword: "sardines", weight: 2, categorySlug: "seafood" },
  { keyword: "fish fingers", weight: 2, categorySlug: "seafood" },
  // Exclusions
  { keyword: "canned tuna", weight: -3, categorySlug: "seafood" },
  { keyword: "tinned tuna", weight: -3, categorySlug: "seafood" },
  { keyword: "canned salmon", weight: -3, categorySlug: "seafood" },
  { keyword: "tinned salmon", weight: -3, categorySlug: "seafood" },
  { keyword: "canned sardines", weight: -3, categorySlug: "seafood" },
  { keyword: "fish sauce", weight: -3, categorySlug: "seafood" },
  { keyword: "fish food", weight: -3, categorySlug: "seafood" },
  { keyword: "frozen fish fingers", weight: -2, categorySlug: "seafood" },

  // ============================================================
  // STATIONERY
  // ============================================================
  // Inherent items
  { keyword: "stationery", weight: 3, categorySlug: "stationery" },
  { keyword: "stationary", weight: 2, categorySlug: "stationery" },
  { keyword: "office supplies", weight: 3, categorySlug: "stationery" },
  { keyword: "school supplies", weight: 3, categorySlug: "stationery" },
  // Pens, pencils & writing instruments
  { keyword: "pens", weight: 3, categorySlug: "stationery" },
  { keyword: "pen", weight: 3, categorySlug: "stationery" },
  { keyword: "ballpoint pen", weight: 3, categorySlug: "stationery" },
  { keyword: "gel pen", weight: 3, categorySlug: "stationery" },
  { keyword: "pencils", weight: 3, categorySlug: "stationery" },
  { keyword: "pencil", weight: 3, categorySlug: "stationery" },
  { keyword: "mechanical pencil", weight: 3, categorySlug: "stationery" },
  { keyword: "colored pencils", weight: 3, categorySlug: "stationery" },
  { keyword: "colouring pencils", weight: 3, categorySlug: "stationery" },
  { keyword: "markers", weight: 3, categorySlug: "stationery" },
  { keyword: "marker", weight: 3, categorySlug: "stationery" },
  { keyword: "permanent marker", weight: 3, categorySlug: "stationery" },
  { keyword: "whiteboard marker", weight: 3, categorySlug: "stationery" },
  { keyword: "highlighters", weight: 3, categorySlug: "stationery" },
  { keyword: "highlighter", weight: 3, categorySlug: "stationery" },
  // Paper, notebooks & mail
  { keyword: "notebook", weight: 3, categorySlug: "stationery" },
  { keyword: "notebooks", weight: 3, categorySlug: "stationery" },
  { keyword: "exercise book", weight: 3, categorySlug: "stationery" },
  { keyword: "exercise books", weight: 3, categorySlug: "stationery" },
  { keyword: "notepad", weight: 3, categorySlug: "stationery" },
  { keyword: "writing pad", weight: 3, categorySlug: "stationery" },
  { keyword: "printer paper", weight: 3, categorySlug: "stationery" },
  { keyword: "a4 paper", weight: 3, categorySlug: "stationery" },
  { keyword: "sticky notes", weight: 3, categorySlug: "stationery" },
  { keyword: "post it notes", weight: 3, categorySlug: "stationery" },
  { keyword: "envelopes", weight: 3, categorySlug: "stationery" },
  { keyword: "envelope", weight: 3, categorySlug: "stationery" },
  // Desk tools & accessories
  { keyword: "sticky tape", weight: 3, categorySlug: "stationery" },
  { keyword: "sellotape", weight: 3, categorySlug: "stationery" },
  { keyword: "glue stick", weight: 3, categorySlug: "stationery" },
  { keyword: "eraser", weight: 3, categorySlug: "stationery" },
  { keyword: "pencil sharpener", weight: 3, categorySlug: "stationery" },
  { keyword: "ruler", weight: 3, categorySlug: "stationery" },
  { keyword: "scissors", weight: 3, categorySlug: "stationery" },
  { keyword: "stapler", weight: 3, categorySlug: "stationery" },
  { keyword: "staples", weight: 3, categorySlug: "stationery" },
  { keyword: "paper clips", weight: 3, categorySlug: "stationery" },
  { keyword: "folders", weight: 3, categorySlug: "stationery" },
  { keyword: "folder", weight: 3, categorySlug: "stationery" },
  { keyword: "binder", weight: 3, categorySlug: "stationery" },
  // Ambiguous terms
  { keyword: "tape", weight: 2, categorySlug: "stationery" },
  { keyword: "glue", weight: 2, categorySlug: "stationery" },
  { keyword: "rubber", weight: 2, categorySlug: "stationery" },
  { keyword: "filing", weight: 2, categorySlug: "stationery" },
  // Exclusions
  { keyword: "duct tape", weight: -2, categorySlug: "stationery" },
  { keyword: "masking tape", weight: -2, categorySlug: "stationery" },
  { keyword: "kitchen scissors", weight: -3, categorySlug: "stationery" },
];
